### ISSUE TITLE
Evosuite should ignore invalid classpath resources

### ISSUE THREAD

**Issue by sinaa** [EvoSuite/evosuite#100]
### Context

Sometimes, elements on the classpath can be non-java classes. For example, when using webjars in maven configuration to load javascript libraries, there will be `.js` files on the classpath.

Evosuite should therefore **not** crash, and simply ignore the invalid (unexpected) resources on the CP.

### Steps to Reproduce

1. Create a simple spring boot application with a javascript dependency
2. Generate tests for any class

_This was tested using the IntelliJ plugin._

### Current Result

```
[MASTER] 13:57:34.804 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1490705854799. Configuration id : null
java.lang.IllegalArgumentException: The class path resource XXXXX\config\javascript\extLibs\http_cdn.jsdelivr.net_sockjs_0.3.4_sockjs.min.js is not valid
	at org.evosuite.classpath.ResourceList.addEntry(ResourceList.java:530) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
	at org.evosuite.classpath.ResourceList.initCache(ResourceList.java:503) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
	at org.evosuite.classpath.ResourceList.getCache(ResourceList.java:485) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
	at org.evosuite.classpath.ResourceList.addEntry(ResourceList.java:512) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
	at org.evosuite.classpath.ResourceList.getAllClasses(ResourceList.java:315) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
	at org.evosuite.classpath.ResourceList.getAllClasses(ResourceList.java:308) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
	at org.evosuite.classpath.ResourceList.getAllClasses(ResourceList.java:289) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
	at org.evosuite.continuous.project.ProjectAnalyzer.getCutsToAnalyze(ProjectAnalyzer.java:152) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
	at org.evosuite.continuous.project.ProjectAnalyzer.analyze(ProjectAnalyzer.java:200) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
	at org.evosuite.continuous.ContinuousTestGeneration.execute(ContinuousTestGeneration.java:157) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
	at org.evosuite.executionmode.Continuous.execute(Continuous.java:131) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
	at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:265) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
	at org.evosuite.EvoSuite.main(EvoSuite.java:301) ~[evosuite-master-1.0.5-8c8931e.jar:1.0.5-SNAPSHOT]
```

**Comment by gofraser** [comment]
It's not a bug, it's a feature - if you specify something invalid on the classpath, wouldn't you like to know? Are you saying that IntelliJ includes Javascript dependencies on the classpath? (Wouldn't that be a bug in IntelliJ?)

**Comment by karthikjeyapal** [comment]
did able to generate the DAO test case , we are used the JPA
