### ISSUE TITLE
Cannot resolve dependency from external library (.jar)

### ISSUE THREAD

**Issue by ohenak** [EvoSuite/evosuite#129]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

I am trying to play around with evosuite by generating test cases for a github project: https://github.com/CyberSource/cybersource-sdk-java. However, EvoSuite cannot generate test cases for some of the classes, for example: com.cybersource.ws.client.HttpClientConnection.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1. `git clone https://github.com/CyberSource/cybersource-sdk-java.git`
2. `mvn compile`
3. `mvn dependency:copy-dependencies`
4. Run the evosuite standalone command as below.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*
`EVOSUITE -class com.cybersource.ws.client.HttpClientConnection -projectCP java/target/dependency:java/target/classes -criterion BRANCH`

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]
```
* EvoSuite 1.0.5
* Going to generate test cases for class: com.cybersource.ws.client.HttpClientConnection
* Starting client
* Connecting to master process on port 9480
* Analyzing classpath:
* Error while initializing target class: org/apache/commons/httpclient/methods/RequestEntity
[MASTER] 14:18:45.404 [logback-2] ERROR TestSuiteGenerator - Problem for com.cybersource.ws.client.HttpClientConnection. Full stack:
java.lang.NoClassDefFoundError: org/apache/commons/httpclient/methods/RequestEntity
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_45]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257) ~[evosuite-1.0.5.jar:1.0.5]
	at org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169) ~[evosuite-1.0.5.jar:1.0.5]
	at org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220) ~[evosuite-1.0.5.jar:1.0.5]
	at org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307) ~[evosuite-1.0.5.jar:1.0.5]
	at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213) ~[evosuite-1.0.5.jar:1.0.5]
	at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55) ~[evosuite-1.0.5.jar:1.0.5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: Class 'org/apache/commons/httpclient/methods/RequestEntity.class' should be in target project, but could not be found!
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:201) ~[evosuite-1.0.5.jar:1.0.5]
	at org.evosuite.instrumentation.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:168) ~[evosuite-1.0.5.jar:1.0.5]
	... 16 common frames omitted
Caused by: java.lang.ClassNotFoundException: Class 'org/apache/commons/httpclient/methods/RequestEntity.class' should be in target project, but could not be found!
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:188) ~[evosuite-1.0.5.jar:1.0.5]
	... 17 common frames omitted
* Computation finished
```
 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

Should be able to generate test cases.

**Comment by sinaa** [comment]
Thanks for submitting this issue.

It seems that the Apache HttpClient dependency is missing from the classpath (`projectCP`), which is why you're getting the class not found exception.

I believe you need to put all individual dependencies on the classpath specifically. The following works (although on this particular class doesn't achieve a high coverage):

    java -jar evosuite.jar -class com.cybersource.ws.client.HttpClientConnection -projectCP $(find java/target/dependency/ | paste -sd ":")":java/target/classes" -criterion BRANCH

**Comment by ohenak** [comment]
Thanks for quick turnaround! I am able to get through the issue. Looks like in this particular class, EvoSuite can't even guess out the correct input for all the instance methods, probably because the input of them is some other classes...?

**Comment by sinaa** [comment]
Evosuite can construct objects based on other classes, but in this particular instance, Evosuite seems to be unable to generate an instance of `HttpClientConnection` without triggering a `NullPointerException`.

Without an instance, it'd be impossible to test the instance methods.

In this particular case, it seems to be because Evosuite is unable to generate an instance of `MerchantConfig` to pass to the `HttpClientConnection`'s constructor. Looking at the `MerchantConfig` class, it seems to be indeed a tough class to automatically generate an instance of.

**Comment by gofraser** [comment]
Seems like the issue can be closed (even though EvoSuite doesn't cover everything it should).
