### ISSUE TITLE
TooManyResourcesException thrown regularly

### ISSUE THREAD

**Issue by rmanash** [EvoSuite/evosuite#135]
I get this exception regularly trying to execute my generated test suites. Regularly means about one or two in 200 test methods which is quite inconvenient when the whole project is much larger than that.

Exception
========
Caused by: org.evosuite.runtime.TooManyResourcesException: Loop has been executed more times than the allowed 10000
                at org.evosuite.runtime.LoopCounter.checkLoop(LoopCounter.java:115)
                at org.apache.xerces.impl.io.UTF8Reader.read(Unknown Source)
                at org.apache.xerces.impl.XMLEntityScanner.load(Unknown Source)
                at org.apache.xerces.impl.XMLEntityScanner.skipSpaces(Unknown Source)
                at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source)
                at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
                at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
                at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
                at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
                at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
                at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
                at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
                at org.apache.poi.util.DocumentHelper.readDocument(DocumentHelper.java:137)
                at org.apache.poi.POIXMLTypeLoader.parse(POIXMLTypeLoader.java:115)
                at org.openxmlformats.schemas.spreadsheetml.x2006.main.StyleSheetDocument$Factory.parse(Unknown Source)
                at org.apache.poi.xssf.model.StylesTable.readFrom(StylesTable.java:203)
                at org.apache.poi.xssf.model.StylesTable.<init>(StylesTable.java:146)

Setup :
java 1.8 64 bit
evosuite 1.0.4
Junit 4.12

My loop execution limit is at 10000. Is there a convenient way to fix/prevent this in general?

**Comment by rmanash** [comment]
Any update please. ?

**Comment by gofraser** [comment]
When generating tests, you could increase the number of loop iterations (-Dmax_loop_iterations=...), or even set it to <= 0 to deactivate this check.

In theory, you could also edit this value in the generated tests (in the scaffolding file you will find the property org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;). However, changing the iteration limit in a generated test suite might lead to other failing tests.

It would be interesting to understand why the number of loop iterations seems to vary at runtime - it seems that there is some non-deterministic code. Is org.apache.poi.xssf.model.StylesTable the class under test?

**Comment by parashuchandra** [comment]
Thank you for the reply gofraser. 
I am also getting the same error as rmanash.

Regarding your question about if org.apache.poi.xssf.model.StylesTable is present in the class under test,
yes,It is being called by the class under test.

**Comment by gofraser** [comment]
But what is the class under test? It would be good to have a class where I can easily reproduce the problem.

**Comment by parashuchandra** [comment]
Please find the below code snippet.When WorkbookFactory.create() method is called ,internally style Table class is being called and throwing the exception.

Inputstream : - input as xlsx file.

public static Iterator<Row> iterator(final InputStream inputStream, final String sheetName) throws IOException, InvalidFormatException {
		Workbook workbook = WorkbookFactory.create(inputStream);
		return iterator(workbook, workbook.getSheetIndex(sheetName));
	}

**Comment by gofraser** [comment]
Thanks. Can you please let me know what the class under test is, so that I can try to reproduce the problem? I can't infer this from this snippet, I'm afraid.

**Comment by parashuchandra** [comment]
Below is the code snippet.Please check.

Test Class
===========   

   @Test
    public void testUploadExcel() throws Exception{
        StatusResponse response = null;
        final InputStream resourceStream = ControllerTest.class.getResourceAsStream("/test.xlsm");
        MultipartFile multipartFile = new MockMultipartFile("test", IOUtils.toByteArray(resourceStream));
        response = Controller.uploadExcel(multipartFile,"AddSite");
        assertNotNull(response);
        assertEquals(response.getStatus(), StatusResponse.SUCCESS_STATUS);
    }
	
	SourceCode Snippet of Controller
	================================
	@ResponseBody
    @RequestMapping(value = "/upload", method = RequestMethod.POST)
    public StatusResponse uploadExcel(@RequestParam("file") MultipartFile file,@RequestParam(value = "flowType", required = true)
    final String flowType) {
        String response;
        try {
            response = OrderUpload.processUploadFile(file.getInputStream(),flowType);
        } catch (Exception e) {
            logger.error("Exception: ", e);
            return StatusResponse.error(e);
        }

        return StatusResponse.success(response);
    }
	
	SourceCode Snippet of OrderUpload
	================================
		public static String processUploadFile(final InputStream inputStream,final String flowType){
		final Map<String,Integer> indexMap = prepareIndexMap(flowType);
		Iterator<Row> uploadFileIterator = null;
		try {
		Workbook workbook = WorkbookFactory.create(inputStream);
		uploadFileIterator = iterator(workbook, workbook.getSheetIndex("Template"));
		}catch(IOException ioe){
			logger.error(" Error Reading in File ",ioe);
		}
		return success;
	}

**Comment by parashuchandra** [comment]
Hi fraser,
Any updates with the issue?

**Comment by loren138** [comment]
I too am having an issue with too many resources.  I think it is continuously counting counting calls to a function if statement which I use for logging so it gets called by all my other functions (hence why it hits 10,000).  It would be nice if I could disable this functionality for a particular class/avoid instrumenting my logging classes.  (I'm actually doing my own instrumentation of the classes under test so they are getting doubly instrumented and my logger is getting instrumented.)

![loop1](https://user-images.githubusercontent.com/1224505/31524382-427dcb22-af87-11e7-8f31-4999c14a72fc.png)

**Comment by loren138** [comment]
Sorry, additional note, -Dmax_loop_iterations must be strictly < 0 to be disabled =0 just disables all loops and if statements from working.  I'm not sure if this was intentional since @gofraser 
commented that =0 would be disabled above (https://github.com/EvoSuite/evosuite/issues/135#issuecomment-326496566) 

Source for checking disabled: https://github.com/EvoSuite/evosuite/blob/32c37290c8adf8b103ca8c52eea52b52ebf924cd/runtime/src/main/java/org/evosuite/runtime/LoopCounter.java#L96
https://github.com/EvoSuite/evosuite/blob/32c37290c8adf8b103ca8c52eea52b52ebf924cd/runtime/src/main/java/org/evosuite/runtime/instrumentation/RuntimeInstrumentation.java#L139
