### ISSUE TITLE
Eclipse Plugin cannot generate test cases 

### ISSUE THREAD

**Issue by csytang** [EvoSuite/evosuite#136]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*
(1) OS: Mac OSX  Sierra(10.12)
(2) Eclipse Luna 4.4.2 
(3) JDK 1.8
(4) Install the plugin using update site: http://www.evosuite.org/update
(5) JUnit 4 installed in my eclipse
(6) Imported the evosuite.jar into the project and added to classpath

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1.
<img width="488" alt="2017-08-31 12 36 04" src="https://user-images.githubusercontent.com/10499238/29906715-59bec174-8e49-11e7-832c-ae24ecb79118.png">
<img width="525" alt="2017-08-31 11 05 00" src="https://user-images.githubusercontent.com/10499238/29906716-5b0594a4-8e49-11e7-9a24-ad7dfe33270a.png">

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*

Nil - using eclipse plugin

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

 Cannot generate the test cases, even after I reinstall the eclipse and reinstall the plugin
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

### Additional info
*Please add any information of interest here below*

**Comment by gofraser** [comment]
Can you provide the console output of Eclipse? There might be some errors produced by EvoSuite in there, if something went wrong. (Not sure where to find the output on a Mac - maybe just start Eclipse from the command line and then you'll see the output in your terminal)

**Comment by csytang** [comment]
Current entry: /Users/tangchris/Downloads/eclipse/plugins/org.evosuite.plugins.eclipse.deps_1.0.5.201705151215/lib/evosuite.jar
Skipping evosuite.jar
Current entry: /Prevayler/evosuite-standalone-runtime-1.0.5.jar
Skipping evosuite.jar
Evosuite JAR is at /Users/tangchris/Downloads/eclipse/plugins/org.evosuite.plugins.eclipse.deps_1.0.5.201705151215/lib/evosuite.jar
Don't need to extract jar
* EvoSuite command: [-generateSuite, -class, org.prevayler.Clock, -evosuiteCP, /Users/tangchris/Downloads/eclipse/plugins/org.evosuite.plugins.eclipse.deps_1.0.5.201705151215/lib/evosuite.jar, -projectCP, /Users/tangchris/Documents/lunaworkspace/Prevayler/lib/commons-logging-1.1.jar:/Users/tangchris/Documents/lunaworkspace/Prevayler/lib/javamatch-0.2.jar:/Users/tangchris/Documents/lunaworkspace/Prevayler/lib/junit-3.8.1.jar:/Users/tangchris/Documents/lunaworkspace/Prevayler/lib/log4j-1.2.13.jar:/Users/tangchris/Documents/lunaworkspace/Prevayler/lib/skaringa-r3p7.jar:/Users/tangchris/Documents/lunaworkspace/Prevayler/lib/xpp3_min-1.1.3_8.jar:/Users/tangchris/Documents/lunaworkspace/Prevayler/lib/xstream-1.1.3.jar:/Users/tangchris/Documents/lunaworkspace/Prevayler/bin, -base_dir, /Users/tangchris/Documents/lunaworkspace/Prevayler, -Dshow_progress=false, -Dstopping_condition=TimeDelta, -Dtest_comments=false, -Dsearch_budget=30, -Dassertion_timeout=30, -Dpure_inspectors=true, -Dnew_statistics=false, -Dsearch_budget=20, -Dglobal_timeout=60, -Dassertions=true, -Dminimize=true, -Dminimize_values=true, -Dreplace_calls=false, -Dreplace_system_in=false, -Dreset_static_fields=false, -Dvirtual_fs=false, -Dlocal_search_rate=10, -Dlocal_search_probability=1.0, -Dlocal_search_adaptation_rate=1.0, -Dlocal_search_selective=true, -Dlocal_search_budget_type=time, -Dlocal_search_budget=15, -Djunit_suffix=_ESTest, -criterion, Line:Branch:Exception:WeakMutation:Output, -Dtest_dir=/Users/tangchris/Documents/lunaworkspace/Prevayler/evosuite-tests]
* EvoSuite 1.0.5-SNAPSHOT
* Going to generate test cases for class: org.prevayler.Clock
* Starting client
* Connecting to master process on port 13120
[MASTER] 21:04:28.762 [Worker-5] ERROR TestGeneration - Not possible to access to clients. Clients' state: Still running. Master registry port: 13120
Results: 0
* Shut down progress monitor
Job returned normally
**********  Markers are disabled
**********  Markers are disabled
Something went wrong while saving test suite after organizing imports
Java Model Exception: Java Model Status [Operation not supported for specified element type(s):Clock_ESTest.java [in <default> [in evosuite-tests/org/prevayler [in Prevayler]]]]
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:785)
	at org.eclipse.jdt.internal.core.CompilationUnit.commitWorkingCopy(CompilationUnit.java:391)
	at org.evosuite.eclipse.popup.actions.TestGenerationJob$4.run(TestGenerationJob.java:280)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3994)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3671)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by csytang** [comment]
It seems the result in saving problem? "Something went wrong while saving test suite after organizing imports"

**Comment by csytang** [comment]
@gofraser

**Comment by gofraser** [comment]
We have updated the Eclipse plugin again, and tested it on Eclipse Mars, Neon, and Oxygen on Windows and Mac. Could you please let us know if the problem persists or is solved?

**Comment by Rajat4440** [comment]
@csytang  @gofraser  did you find any solution for above Issue?

I am also facing same issue while generating test cases using Evosuite.
Please suggest if you have any solution.

**Comment by neerajsharma543** [comment]
Is there any resolution on this? I am still facing this issue

**Comment by tushartawde** [comment]
I am also facing same issue while generating test cases using Evosuite.
Can u Please help.

**Comment by sravanisbv** [comment]
I followed below steps but not able to get "generate tests with Evosuite" option in eclipse
(1) OS: windows(7:32bit)
(2) Eclipse Luna 4.4.2
(3) JDK 1.8
(4) Installed the plugin using update site: http://www.evosuite.org/update
(5) JUnit 4 installed in my eclipse
(6) Imported the evosuite.jar into the project and added to classpath

should I add something else or run any cmds to get that Generate tests with evosuite option in eclipse
