### ISSUE TITLE
IntelliJ 15 ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by void01** [EvoSuite/evosuite#16]
Issue with IntelliJ EvoSuite plugin.
Steps to reproduce:
1) Right click within a method 
2) Select Run EvoSuite
3) Exception thrown:

```
java.lang.ArrayIndexOutOfBoundsException: 0
    at org.evosuite.intellij.util.Utils.getFolderLocation(Utils.java:61)
    at org.evosuite.intellij.EvoAction.getCUTsToTest(EvoAction.java:139)
    at org.evosuite.intellij.EvoAction.actionPerformed(EvoAction.java:84)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
    at java.awt.Component.processMouseEvent(Component.java:6543)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6308)
    at java.awt.Container.processEvent(Container.java:2235)
    at java.awt.Component.dispatchEventImpl(Component.java:4899)
    at java.awt.Container.dispatchEventImpl(Container.java:2293)
    at java.awt.Component.dispatchEvent(Component.java:4721)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4461)
    at java.awt.Container.dispatchEventImpl(Container.java:2279)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4721)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:724)
    at java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by arcuri82** [comment]
Hi,
  I am not able to replicate that exception, but the involved code is:

```
public static String getFolderLocation(Module module){
        ModuleRootManager rootManager = ModuleRootManager.getInstance(module);
        VirtualFile[] contentRoots = rootManager.getContentRoots(); 
        return new File(contentRoots[0].getCanonicalPath()).getAbsolutePath();
    }
```

which is using IntelliJ libraries. Somehow, it seems there is something different in your project, where  at least one module has no root folder. I can make a workaround (eg skip the handling of that module), but would be interested to know how it can happen in the first place. Is there anything special in the structure of your project? If it is open source, can you point me to it?

cheers

Andrea

**Comment by void01** [comment]
Not all my modules have src's. I have attached what my project looks like.
<img width="465" alt="screen shot 2016-02-10 at 7 17 25 am" src="https://cloud.githubusercontent.com/assets/17126133/12948273/9f9c500a-cfc6-11e5-8266-37eaa6ad16be.png">
<img width="446" alt="screen shot 2016-02-10 at 7 18 21 am" src="https://cloud.githubusercontent.com/assets/17126133/12948274/9f9cd0ac-cfc6-11e5-8686-b3c12f98417a.png">

**Comment by arcuri82** [comment]
The problem does not seem related to "src", as `rootManager.getContentRoots()` (should) points to the location of the module itself. I have been trying to reproduce the issue (eg by playing with different kinds of modules), but did not manage. And in the screenshot you sent I do not recognize anything that is a clear problem. Can you please try to recreate (eg if you cannot share the full one) a project in which this issue happens, zip it and post it here?  so i can debug it. thanks

**Comment by arcuri82** [comment]
although i could not reproduce it, i made a possible workaround, which is now present in the new 1.0.3 release. Can you please update your EvoSuite and check if problem persists? 

thanks

Andrea

**Comment by void01** [comment]
That is gone but now a new issue exists. The message states, "No '.java' file or non-empty source folder was selected in a valid module".

**Comment by arcuri82** [comment]
To generate tests for some classes, you need to select their ".java" files in the project view, or a folder containing them. Or are you saying that you are getting that message even if .java files are selected?

**Comment by void01** [comment]
I have selected the .java file and i get that error.
<img width="1358" alt="screen shot 2016-02-24 at 6 35 46 pm" src="https://cloud.githubusercontent.com/assets/17126133/13306016/88532b20-db25-11e5-96f7-4dff6395ff1d.png">

**Comment by Kavya7** [comment]
hi  Did your problem get resolved?
Even i am facing same issue in intellij 15 when trying to run evosuite

**Comment by arcuri82** [comment]
Hi @Kavya7 ,
  I have been unable to reproduce this issue, even on different machines :( 
Can you please specify which OS, IntellIJ, EvoSuite and JDK versions you are using?  If you are working on an open-source project, can you provide the link? Problem is that at the moment I am not even sure if it is a configuration issue or something special in the tested project that leads to  this error

cheers

Andrea

**Comment by void01** [comment]
I think its a configuration issue with my project because i can't reproduce the error with a new project with similar structure.

**Comment by Kavya7** [comment]
Hi arcuri
My project is not open source so i cannot share it.
I am able to simulate above issue by creating dummy project and i see that if project directory location and Module location(or content Root) is in different directory  then you observe the issue.[Even in my project this is the scenario]

![image](https://cloud.githubusercontent.com/assets/18523151/15204033/ec192946-1826-11e6-838c-f292de29dae5.png)

Thanks for the help!!!!

**Comment by arcuri82** [comment]
Hi @Kavya7 ,
  I tried to create a project as you showed, but still I do not see that issue, at least not on IntelliJ 15 on a Mac using EvoSuite 1.0.3. Which versions of IntelliJ/EvoSuite are you using?  Can you zip that dummy project and attach it here?

cheers

Andrea

**Comment by Kavya7** [comment]
Hi Arcuri

i am using intellij 15 on widows 7.
Evosuite version:1.0.3

Attaching zipped file:
[Evosuite.zip](https://github.com/EvoSuite/evosuite/files/267318/Evosuite.zip)

Thanks a lot!!!

**Comment by arcuri82** [comment]
Hi,
  now I can reproduce the issue by using that Evosuite.zip. I see why it is failing, but not sure how to best handle it, as it seems a quite a peculiar project structure. How and why did you create it like that? Was there any specific reason? I mean:

evosuite1_3
|- ContentRoot
   |- src
      |- src
         |- EvoTest.java
|- EvoTest  
  |- .idea

The actual IntelliJ project is in the EvoTest folder, but that refers to the external ContentRoot for the src code. As it is now, IntelliJ plugin only works on src folders that are inside the module, not external, as that is the general case for example when using projects based on Maven (not sure if it is the same for Ant/Gradle). I could try to look into how to handle external src folders in IntelliJ, but I would need some more info on how such type of project structure was generated in the first place (ie is it a common case? is it just and edge case?).

cheers

**Comment by arcuri82** [comment]
and of course I pressed "Comment" before looking at how Markdown would had removed all the indentation... 

```
evosuite1_3
|- ContentRoot
   |- src
       |- src
           |- EvoTest.java
|- EvoTest
    |- .idea
```
