### ISSUE TITLE
java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by ancgate** [EvoSuite/evosuite#174]
**I have followed all the steps to generate test by using the command 

mvn evosuite:generate**

[INFO] Going to generate tests with EvoSuite
[INFO] Total memory: 800mb
[INFO] Time per class: 2 minutes
[INFO] Number of used cores: 1
[INFO] Target: /Users/jeffersonbienaime/Downloads/Developer Corner/MerQury Projects/JavaFXDesktopAPP/Herudi/phoebe/target/classes
[INFO] Basedir: /Users/jeffersonbienaime/Downloads/Developer Corner/MerQury Projects/JavaFXDesktopAPP/Herudi/phoebe
[INFO] Started spawn process manager on port 58434
[INFO] SLF4J: Class path contains multiple SLF4J bindings.
[INFO] SLF4J: Found binding in [jar:file:/Users/jeffersonbienaime/.m2/repository/org/evosuite/evosuite-master/1.0.5/evosuite-master-1.0.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[INFO] SLF4J: Found binding in [jar:file:/Users/jeffersonbienaime/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[INFO] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[INFO] SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[INFO] * EvoSuite 1.0.5
[INFO] Registered remote process from /127.0.0.1:58436
[INFO] Going to execute 26 jobs
[INFO] Estimated completion time: 52 minutes, by 2018-02-21T13:53:10.557
[INFO] Going to start job for: com.merqury.phoebe.filter.AuthorizationFilter. Expected to end in 710 seconds, by 2018-02-21T13:13:00.581
[INFO] Registered remote process from /127.0.0.1:58437
[INFO] Registered remote process from /127.0.0.1:58443

**Unfortunately, classes are not generated. This is what I am getting and it is the same for all classes.**

[MASTER] 12:44:28.485 [pool-2-thread-1] ERROR TestSuiteGenerator - Problem for com.merqury.phoebe.beans.AbstractFacade. Full stack:
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/evosuite/instrumentation/BytecodeInstrumentation.handleStaticReset(Ljava/lang/String;Lorg/objectweb/asm/ClassVisitor;)Lorg/objectweb/asm/ClassVisitor; @39: invokespecial
  Reason:
    Type 'org/evosuite/runtime/instrumentation/CreateClassResetClassAdapter' (current frame, stack[2]) is not assignable to 'org/objectweb/asm/ClassVisitor'
  Current Frame:
    bci: @39
    flags: { }
    locals: { 'java/lang/String', 'org/evosuite/runtime/instrumentation/CreateClassResetClassAdapter', 'org/evosuite/runtime/instrumentation/CreateClassResetClassAdapter' }
    stack: { uninitialized 33, uninitialized 33, 'org/evosuite/runtime/instrumentation/CreateClassResetClassAdapter', 'java/lang/String' }
  Bytecode:
    0x0000000: b200 8299 0011 bb00 8359 2b2a 04b7 0084
    0x0000010: 4da7 000e bb00 8359 2b2a 03b7 0084 4d2c
    0x0000020: 4cbb 0085 592b 2ab7 0086 4e2d 4c2b b0  
  Stackmap Table:
    same_frame(@20)
    append_frame(@31,Object[#215])

	at org.evosuite.instrumentation.InstrumentingClassLoader.<init>(InstrumentingClassLoader.java:67) ~[evosuite-client-1.0.5.jar:na]
	at org.evosuite.TestGenerationContext.<init>(TestGenerationContext.java:97) ~[evosuite-client-1.0.5.jar:na]
	at org.evosuite.TestGenerationContext.<clinit>(TestGenerationContext.java:74) ~[evosuite-client-1.0.5.jar:na]
	at org.evosuite.testcase.execution.TestCaseExecutor.execute(TestCaseExecutor.java:332) ~[evosuite-client-1.0.5.jar:na]
	at org.evosuite.testcase.execution.TestCaseExecutor.execute(TestCaseExecutor.java:277) ~[evosuite-client-1.0.5.jar:na]
	at org.evosuite.TestSuiteGenerator.initializeTargetClass(TestSuiteGenerator.java:97) ~[evosuite-client-1.0.5.jar:na]
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:130) ~[evosuite-client-1.0.5.jar:na]
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) [evosuite-client-1.0.5.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
[MASTER] 12:44:28.490 [pool-2-thread-1] ERROR ClientNodeImpl - Error when generating tests for: com.merqury.phoebe.beans.AbstractFacade with seed 1519235068198. Configuration id : default
java.lang.NoClassDefFoundError: Could not initialize class org.evosuite.TestGenerationContext
	at org.evosuite.result.TestGenerationResultBuilder.resetTestData(TestGenerationResultBuilder.java:94) ~[evosuite-client-1.0.5.jar:na]
	at org.evosuite.result.TestGenerationResultBuilder.<init>(TestGenerationResultBuilder.java:77) ~[evosuite-client-1.0.5.jar:na]
	at org.evosuite.result.TestGenerationResultBuilder.getInstance(TestGenerationResultBuilder.java:82) ~[evosuite-client-1.0.5.jar:na]
	at org.evosuite.result.TestGenerationResultBuilder.buildErrorResult(TestGenerationResultBuilder.java:50) ~[evosuite-client-1.0.5.jar:na]
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:169) ~[evosuite-client-1.0.5.jar:na]
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) ~[evosuite-client-1.0.5.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

**Comment by gofraser** [comment]
Can you confirm whether this also happens with the current head version on GitHub (e.g. by applying that directly to com.merqury.phoebe.beans.AbstractFacade)? Or could you point me to where to find this class com.merqury.phoebe.beans.AbstractFacade?

**Comment by ancgate** [comment]
my code  is here:
 https://github.com/ancgate/phoebeRC.git
It is happening for all the classes. I will with the current head version on Github.

**Comment by gofraser** [comment]
I don't get to see exactly that error, but loads of other issues, with any recent version of EvoSuite. This will need some debugging - I can't promise how soon I'll find the time for this, but I'll look into it as soon as I can.

**Comment by ancgate** [comment]
Ok, Thanks, in the meantime, I will look into it as well, if I find the solution, I will let you know.

**Comment by gofraser** [comment]
Actually, I accidentally had EvoSuite 1.0.5 on the classpath (I just used all dependencies given by Maven). With the current head version I do get some tests and no crash. (Although there's a good number of warning messages from EvoSuite about missing dependency classes)

**Comment by ancgate** [comment]
I was able to generate some classes through the mvn evosuite:generate. I removed a duplicate (evosuite-maven-plugin both in build and dependencies) as well as the 

<repositories>
        <repository>
            <id>EvoSuite</id>
            <name>EvoSuite Repository</name>
            <url>http://www.evosuite.org/m2</url>
        </repository>
</repositories> in my pom.xml

However, It generates only 11 classes out of 26. That is weird. I attached the logs for class that was not created. 

[std_err_CLIENT.log](https://github.com/EvoSuite/evosuite/files/1745548/std_err_CLIENT.log)
[std_err_MASTER.log](https://github.com/EvoSuite/evosuite/files/1745549/std_err_MASTER.log)
[std_out_CLIENT.log](https://github.com/EvoSuite/evosuite/files/1745550/std_out_CLIENT.log)
[std_out_MASTER.log](https://github.com/EvoSuite/evosuite/files/1745551/std_out_MASTER.log)

**Comment by ancgate** [comment]
I will close this issue since the initial error has been solved. java.lang.VerifyError: Bad type on operand stack.
