### ISSUE TITLE
Individual test generation strategy is broken with new archive

### ISSUE THREAD

**Issue by gofraser** [EvoSuite/evosuite#180]
Optimising individual tests instead of test suites causes EvoSuite to crash in the refactored archive:

```
[MASTER] 23:10:27.377 [RMI TCP Connection(3)-127.0.0.1] WARN  SearchStatistics - searchStatistics expected a TestSuiteChromosome
[MASTER] 23:10:27.864 [logback-2] ERROR ClientNodeImpl - Error when generating tests for: org.apache.commons.cli.Option with seed 1523049024871. Configuration id : null
java.lang.ClassCastException: org.evosuite.testcase.TestChromosome cannot be cast to org.evosuite.testsuite.TestSuiteChromosome
	at org.evosuite.ga.archive.CoverageArchive.mergeArchiveAndSolution(CoverageArchive.java:259) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.ga.archive.CoverageArchive.mergeArchiveAndSolution(CoverageArchive.java:43) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.ga.metaheuristics.GeneticAlgorithm.updateBestIndividualFromArchive(GeneticAlgorithm.java:1040) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.TimeController.execute(TimeController.java:112) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.ga.metaheuristics.MonotonicGA.generateSolution(MonotonicGA.java:315) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.strategy.IndividualTestStrategy.generateTests(IndividualTestStrategy.java:184) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.TestSuiteGenerator.generateTests(TestSuiteGenerator.java:653) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:236) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
* Computation finished
```

To reproduce this, just run EvoSuite on any class using `-generateTests`

**Comment by jose** [comment]
As `IndividualTestStrategy` is implemented, it does not seem to make any sense to use an archive for this particular strategy. What do you think?

**Comment by gofraser** [comment]
I agree that for the IndividualTestStrategy we can deactivate the archive.

Are there possible other algorithms affected by this (e.g., MOSA, Sina's regression stuff, different flavours of random testing, ...)? This might require (2), or deactivating the archive for all of them.
