### ISSUE TITLE
How to enable the dependency Jars in classpath?

### ISSUE THREAD

**Issue by saiksrin** [EvoSuite/evosuite#185]
Context
I tried to generate unit-test cases for a classfile called PersistenceUtil. It internally depends on "Log4J & InfraMgr" jars. I'm getting class not found exception how to add multiple jars in the evosuite CLI.

EvoSuite Arguments

C:\Users\Administrator>%evosuite% -class com.network.PersistenceUtil -projectCP f:\APR_04\NetworkController\bin -target "f:\projJars\inframgr-1.0-SNAPSHOT.jar"

Current Result

Response i'm getting after the command:

* EvoSuite 1.0.5
* Going to generate test cases for class: com.network.PersistenceUtil
* Starting client
* Properties loaded from C:\Users\Administrator\evosuite-files\evosuite.properties
* Connecting to master process on port 19546
* Analyzing classpath:
* Error while initializing target class: org/apache/log4j/Logger
[MASTER] 16:01:49.712 [logback-2] ERROR TestSuiteGenerator - Problem for com.network.PersistenceUtil. Full stack:
java.lang.NoClassDefFoundError: org/apache/log4j/Logger
        at com.PersistenceUtil.<clinit>(PersistenceUtil.java) ~[bin/:na]
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_161]
        at java.lang.Class.forName(Unknown Source) ~[na:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_161]
        at org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257) ~[evosuite-1.0.5.jar:1.0.5]
        at org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169) ~[evosuite-1.0.5.jar:1.0.5]
        at org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220) ~[evosuite-1.0.5.jar:1.0.5]
        at org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307) ~[evosuite-1.0.5.jar:1.0.5]
        at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213) ~[evosuite-1.0.5.jar:1.0.5]
        at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55) ~[evosuite-1.0.5.jar:1.0.5]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_161]
Caused by: java.lang.ClassNotFoundException: Class 'org/apache/log4j/Logger.class' should be in target project, but could not be found!
        at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:201) ~[evosuite-1.0.5.jar:1.0.5]
        at org.evosuite.instrumentation.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:168) ~[evosuite-1.0.5.jar:1.0.5]
        ... 17 common frames omitted
Caused by: java.lang.ClassNotFoundException: Class 'org/apache/log4j/Logger.class' should be in target project, but could not be found!
        at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:188) ~[evosuite-1.0.5.jar:1.0.5]
        ... 18 common frames omitted
* Computation finished
[MASTER] 16:01:52.261 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 16:01:52.367 [main] ERROR TestGeneration - failed to write statistics data

 
Expected result
It should generate Junit files without fail.

Additional info
I need a info on how to add multiple dependency jars for a class. I'm using windows machine running evosuite via CLI & also i'm not using maven in my project. Currently I'm using ant & gradle. Please point me out if any developer guide is available for EVOSUITE.

**Comment by jose** [comment]
> I need a info on how to add multiple dependency jars for a class. I'm using windows machine running evosuite via CLI & also i'm not using maven in my project.

`-projectCP f:\APR_04\NetworkController\bin;__path_to_jar_1__;__path_to_jar_2__`

> Please point me out if any developer guide is available for EVOSUITE.

- [Using EvoSuite on the Commandline](http://www.evosuite.org/documentation/commandline/)
- [Tutorial Part 1: EvoSuite on the Command Line](http://www.evosuite.org/documentation/tutorial-part-1/)
- [Tutorial Part 3: Running Experiments](http://www.evosuite.org/documentation/tutorial-part-3/)
- [Tutorial Part 4: Extending EvoSuite](http://www.evosuite.org/documentation/tutorial-part-4/)
