### ISSUE TITLE
Maven Evosuite test creation fails with OutOfMemoryError errors

### ISSUE THREAD

**Issue by kpepper** [EvoSuite/evosuite#186]
Hi, I am attempting to create Evosuite tests using release 1.0.6 from Maven, Java 1.8 on an 8GB Mac. Hence I'm executing:

mvn -DmemoryInMB=4000 -Dcores=2 evosuite:generate evosuite:export

As I want to use Jacoco coverage reporting I've set -Duse_separate_classloader=false in extraArgs property of the evosuite maven plugin. After waiting a couple of hours, the build bombs with an out of memory error without creating any tests. If I set -Duse_separate_classloader=true with all other settings the same, then tests seem to get created (although presumably Jacoco won't work then). There are 500 odd classes to create tests for. 
I can't create anything with use_separate_classloader=false. I've also tried with 2GB and 4.5GB memory specified.

Does it need a massive amount of memory? Or may be there's a memory leak?

**Comment by kpepper** [comment]
**@doyo3141** Thanks for the suggestion. Yes it works when doing the global replace. But, seems like there could be something weird going on when setting it via <extraArgs>.

**Comment by kpepper** [comment]
I think the separate classloader flag discussed above was a red herring. I'm finding it very difficult to get any test generation at all. Only one run has succeeded without heap memory errors and even then the coverage was not great (i.e. some classes with no tests at all).

Here's an example log using just default settings:

mvn -Dconsider_main_methods=false evosuite:clean evosuite:generate evosuite:export evosuite:prepare

Going to generate tests with EvoSuite
[INFO] Total memory: 800mb
[INFO] Time per class: 2 minutes
[INFO] Number of used cores: 1
[INFO] Target: /home/application/target/classes
[INFO] Basedir: /home/application
[INFO] Started spawn process manager on port 49492
[INFO] SLF4J: Class path contains multiple SLF4J bindings.
[INFO] SLF4J: Found binding in [jar:file:/home/.m2/repository/org/evosuite/evosuite-master/1.0.6/evosuite-master-1.0.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[INFO] SLF4J: Found binding in [jar:file:/home/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[INFO] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[INFO] SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[INFO] * EvoSuite 1.0.6
[INFO] Registered remote process from /127.0.0.1:49493
[INFO] Exception in thread "Thread-0" java.lang.OutOfMemoryError: Java heap space
[INFO] 	at java.util.regex.Matcher.<init>(Matcher.java:226)
[INFO] 	at java.util.regex.Matcher.toMatchResult(Matcher.java:250)
[INFO] 	at java.util.Scanner.match(Scanner.java:1294)
[INFO] 	at java.util.Scanner.nextLine(Scanner.java:1541)
[INFO] 	at org.evosuite.utils.SpawnProcessKeepAliveChecker$2.run(SpawnProcessKeepAliveChecker.java:137)
[INFO] [MASTER] 12:24:05.642 [main] WARN  ProjectAnalyzer - Cannot handle package.class1 due to: class java.lang.ClassNotFoundException Java heap space
[INFO] [MASTER] 13:02:33.692 [main] WARN  ProjectAnalyzer - Cannot handle Cannot handle package.class2 due to: class java.lang.ClassNotFoundException Java heap space
[INFO] Exception in thread "AWT-Shutdown" java.lang.OutOfMemoryError: Java heap space
[INFO] [MASTER] 13:06:57.055 [main] WARN  ProjectAnalyzer - Cannot handle Cannot handle package.class3 due to: class java.lang.ClassNotFoundException Java heap space
[INFO] [MASTER] 13:08:26.170 [main] WARN  ProjectAnalyzer - Cannot handle Cannot handle package.class4 due to: class java.lang.ClassNotFoundException Java heap space
[INFO] [MASTER] 13:39:47.771 [main] WARN  ProjectAnalyzer - Cannot handle package.class5 due to: class java.lang.ClassNotFoundException Java heap space
[INFO] Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AWT-Shutdown"

etc, etc

[INFO] [MASTER] 13:49:15.982 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1524833293531. Configuration id : null
[INFO] java.lang.OutOfMemoryError: Java heap space
[ERROR] Error in EvoSuite
[INFO] Stopping spawn process manager
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:23 h
[INFO] Finished at: 2018-04-27T13:49:20+01:00
[INFO] Final Memory: 18M/130M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.evosuite.plugins:evosuite-maven-plugin:1.0.6:generate (default-cli) on project application: Failed to correctly execute EvoSuite -> [Help 1]

Maven plugin definition:

                                <plugin>
			        <groupId>org.evosuite.plugins</groupId>
			        <artifactId>evosuite-maven-plugin</artifactId>
			        <version>${evosuite.plugin.version}</version>
			        <executions>
			        		<execution>
			        			<id>create-evosuite-tests</id>
	         				<goals> 
	         					<goal>prepare</goal> 
	         				</goals>
	         				<phase>process-test-classes</phase>
	      				</execution>
	      			</executions>
				</plugin>

Is this only possible now on a multi-cpu server with >8GB? I was previously using ant on 1.0.5 and didn't have this issue. Is there any way to partition the test creation into manageable chunks that won't cause heap exhaustion or some other options to try? Thanks.

**Comment by gofraser** [comment]
As I understand it, you are getting the error during test generation -- the `-Duse_separate_classloader` can't really have any effects on EvoSuite during test generation, it only changes how code is instrumented during test execution (after EvoSuite has finished).

Is there an example project on which I could reproduce the memory issues?

**Comment by gofraser** [comment]
Yes, EvoSuite mocks URL access.

EvoSuite launches a separate process for each target class, so partitioning should not make a difference.

The `memoryInMB` option affects what these sub-processes (one per class) get, `-Xmx` would only affect the master process (which doesn't do any test generation). In your case it does seem that this master process had memory issues, so using `-Xmx` might be worth a try. Was this a particularly large project with many classes?

**Comment by kpepper** [comment]
Yes, around 600 classes I think. I Will try a rerun this week and let you know.

**Comment by gofraser** [comment]
Thanks! Is the project you're applying this available somewhere? Or is there an open source project on which you can manage to reproduce this?

**Comment by kpepper** [comment]
No, not at the moment.

**Comment by gofraser** [comment]
I am struggling to reproduce this. I also suspect that the stacktrace is not really giving us a hint, since the OOM error can happen anywhere once memory is short. 

My first guess would be that the problem is that EvoSuite Maven plugin ignores MAVEN_OPTS when spawning a JVM, and that the default heap size is too small. Could you determine what your default heap size is on your machine? (See: https://stackoverflow.com/questions/4667483/how-is-the-default-java-heap-size-determined)

Maybe also try running the same, but setting _JAVA_OPTIONS instead of (or in addition to) MAVEN_OPTS, which should lead to these options being passed to all newly forked JVM processes.
