### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager

### ISSUE THREAD

**Issue by yanli09** [EvoSuite/evosuite#198]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

I have one simple maven based java project, and this project only has one class as below 

package evosuite.maven.test;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Hello world!
 *
 */
public class App 
{
    private static final Logger log = LogManager.getLogger(App.class);

    public static void main( String[] args )
    {
        log.info( "Hello World!" );
    }
}

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1. check out the latest master code base of Evosuite 
2. create the above project on local window path D:\dev\github\evosuitemaventest
3. compile the project as mvn compile
4.  set the run configuration within Idea as below
    main class: org.evosuite.EvoSuite
   vm options:blank
   program arguments: -target  D:\dev\github\evosuitemaventest\target\classes
   working directory:  D:\dev\github\evosuite
5. run or debug the org.evosuite.EvoSuite within idea

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*
-target  D:\dev\github\evosuitemaventest\target\classes

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]
"C:\Program Files\Java\jdk1.8.0_151\bin\java" "-javaagent:D:\developInstallation\IntelliJ IDEA 2017.3.3\lib\idea_rt.jar=55547:D:\developInstallation\IntelliJ IDEA 2017.3.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_151\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\rt.jar;D:\dev\github\evosuite\master\target\classes;D:\dev\github\evosuite\runtime\target\classes;D:\.m2\repository\org\mockito\mockito-core\2.16.0\mockito-core-2.16.0.jar;D:\.m2\repository\net\bytebuddy\byte-buddy\1.7.9\byte-buddy-1.7.9.jar;D:\.m2\repository\net\bytebuddy\byte-buddy-agent\1.7.9\byte-buddy-agent-1.7.9.jar;D:\.m2\repository\org\objenesis\objenesis\2.6\objenesis-2.6.jar;D:\.m2\repository\javax\ejb\javax.ejb-api\3.2\javax.ejb-api-3.2.jar;D:\.m2\repository\javax\transaction\javax.transaction-api\1.2\javax.transaction-api-1.2.jar;D:\.m2\repository\javax\faces\javax.faces-api\2.2\javax.faces-api-2.2.jar;D:\.m2\repository\javax\ws\rs\jsr311-api\1.1.1\jsr311-api-1.1.1.jar;D:\.m2\repository\org\hibernate\hibernate-core\5.2.13.Final\hibernate-core-5.2.13.Final.jar;D:\.m2\repository\org\jboss\logging\jboss-logging\3.3.1.Final\jboss-logging-3.3.1.Final.jar;D:\.m2\repository\org\hibernate\javax\persistence\hibernate-jpa-2.1-api\1.0.0.Final\hibernate-jpa-2.1-api-1.0.0.Final.jar;D:\.m2\repository\org\javassist\javassist\3.22.0-GA\javassist-3.22.0-GA.jar;D:\.m2\repository\antlr\antlr\2.7.7\antlr-2.7.7.jar;D:\.m2\repository\org\jboss\spec\javax\transaction\jboss-transaction-api_1.2_spec\1.0.1.Final\jboss-transaction-api_1.2_spec-1.0.1.Final.jar;D:\.m2\repository\org\jboss\jandex\2.0.3.Final\jandex-2.0.3.Final.jar;D:\.m2\repository\com\fasterxml\classmate\1.3.0\classmate-1.3.0.jar;D:\.m2\repository\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar;D:\.m2\repository\org\hibernate\common\hibernate-commons-annotations\5.0.1.Final\hibernate-commons-annotations-5.0.1.Final.jar;D:\.m2\repository\org\hsqldb\hsqldb\2.4.0\hsqldb-2.4.0.jar;D:\.m2\repository\org\springframework\spring-orm\4.3.14.RELEASE\spring-orm-4.3.14.RELEASE.jar;D:\.m2\repository\org\springframework\spring-beans\4.3.14.RELEASE\spring-beans-4.3.14.RELEASE.jar;D:\.m2\repository\org\springframework\spring-core\4.3.14.RELEASE\spring-core-4.3.14.RELEASE.jar;D:\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;D:\.m2\repository\org\springframework\spring-jdbc\4.3.14.RELEASE\spring-jdbc-4.3.14.RELEASE.jar;D:\.m2\repository\org\springframework\spring-tx\4.3.14.RELEASE\spring-tx-4.3.14.RELEASE.jar;D:\.m2\repository\org\springframework\spring-context\4.3.14.RELEASE\spring-context-4.3.14.RELEASE.jar;D:\.m2\repository\org\springframework\spring-aop\4.3.14.RELEASE\spring-aop-4.3.14.RELEASE.jar;D:\.m2\repository\org\springframework\spring-expression\4.3.14.RELEASE\spring-expression-4.3.14.RELEASE.jar;D:\.m2\repository\org\slf4j\slf4j-api\1.7.22\slf4j-api-1.7.22.jar;C:\Program Files\Java\jdk1.8.0_151\lib\tools.jar;D:\.m2\repository\org\ow2\asm\asm\6.0\asm-6.0.jar;D:\.m2\repository\org\ow2\asm\asm-commons\6.0\asm-commons-6.0.jar;D:\.m2\repository\org\ow2\asm\asm-tree\6.0\asm-tree-6.0.jar;D:\.m2\repository\org\ow2\asm\asm-analysis\6.0\asm-analysis-6.0.jar;D:\.m2\repository\org\ow2\asm\asm-util\6.0\asm-util-6.0.jar;D:\.m2\repository\junit\junit\4.12\junit-4.12.jar;D:\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;D:\.m2\repository\javax\xml\bind\jaxb-api\2.3.0\jaxb-api-2.3.0.jar;D:\.m2\repository\com\opencsv\opencsv\4.1\opencsv-4.1.jar;D:\.m2\repository\org\apache\commons\commons-text\1.1\commons-text-1.1.jar;D:\.m2\repository\commons-beanutils\commons-beanutils\1.9.3\commons-beanutils-1.9.3.jar;D:\.m2\repository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;D:\.m2\repository\dk\brics\automaton\automaton\1.11-8\automaton-1.11-8.jar;D:\.m2\repository\ch\qos\logback\logback-classic\1.1.3\logback-classic-1.1.3.jar;D:\.m2\repository\ch\qos\logback\logback-core\1.1.3\logback-core-1.1.3.jar;D:\.m2\repository\com\googlecode\gentyref\gentyref\1.2.0\gentyref-1.2.0.jar;D:\.m2\repository\net\sf\jgrapht\jgrapht\0.8.3\jgrapht-0.8.3.jar;D:\.m2\repository\com\thoughtworks\xstream\xstream\1.4.10\xstream-1.4.10.jar;D:\.m2\repository\xmlpull\xmlpull\1.1.3.1\xmlpull-1.1.3.1.jar;D:\.m2\repository\xpp3\xpp3_min\1.1.4c\xpp3_min-1.1.4c.jar;D:\.m2\repository\org\apache\commons\commons-lang3\3.7\commons-lang3-3.7.jar;D:\.m2\repository\commons-io\commons-io\2.6\commons-io-2.6.jar;D:\.m2\repository\commons-cli\commons-cli\1.4\commons-cli-1.4.jar;D:\.m2\repository\org\kohsuke\graphviz-api\1.1\graphviz-api-1.1.jar;D:\.m2\repository\oro\oro\2.0.8\oro-2.0.8.jar;D:\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;D:\dev\github\evosuite\client\target\classes;D:\.m2\repository\org\jboss\spec\javax\servlet\jboss-servlet-api_3.1_spec\1.0.2.Final\jboss-servlet-api_3.1_spec-1.0.2.Final.jar;D:\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;D:\.m2\repository\javax\enterprise\cdi-api\1.2\cdi-api-1.2.jar;D:\.m2\repository\javax\el\javax.el-api\3.0.0\javax.el-api-3.0.0.jar;D:\.m2\repository\javax\interceptor\javax.interceptor-api\1.2\javax.interceptor-api-1.2.jar" org.evosuite.EvoSuite -target D:\dev\github\evosuitemaventest\target\classes
* EvoSuite 
* Found 1 matching classes in target D:\dev\github\evosuitemaventest\target\classes
* Analyzing classpath (generating inheritance tree)
  - D:\dev\github\evosuitemaventest\target\classes
* Current class: evosuite.maven.test.App
* Going to generate test cases for class: evosuite.maven.test.App
* Starting client
* Connecting to master process on port 14283
* Analyzing classpath: 
* Error while initializing target class: org/apache/logging/log4j/LogManager
[MASTER] 10:29:45.373 [logback-2] ERROR TestSuiteGenerator - Problem for evosuite.maven.test.App. Full stack:
java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at evosuite.maven.test.App.<clinit>(App.java) ~[classes/:na]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_151]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257) ~[classes/:na]
	at org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169) ~[classes/:na]
	at org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220) ~[classes/:na]
	at org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307) ~[classes/:na]
	at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213) ~[classes/:na]
	at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55) ~[classes/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: Class 'org/apache/logging/log4j/LogManager.class' should be in target project, but could not be found!
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:201) ~[classes/:na]
	at org.evosuite.instrumentation.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:168) ~[classes/:na]
	... 17 common frames omitted
Caused by: java.lang.ClassNotFoundException: Class 'org/apache/logging/log4j/LogManager.class' should be in target project, but could not be found!
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:188) ~[classes/:na]
	... 18 common frames omitted
* Computation finished
[MASTER] 10:29:47.840 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 10:29:47.941 [main] ERROR TestGeneration - failed to write statistics data

Process finished with exit code 0

 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*
without any error

### Additional info
*Please add any information of interest here below*

**Comment by yanli09** [comment]
![idea setting](https://user-images.githubusercontent.com/3969986/40595002-d20b97f2-6264-11e8-93b6-288dd2ae9b2a.png)

**Comment by yanli09** [comment]
[evosuitemaventest.zip](https://github.com/EvoSuite/evosuite/files/2043396/evosuitemaventest.zip)

**Comment by prathmesh-halgekar** [comment]
This is happening only in the case of Log4j.
Possible fix tried: Removing 'org.apache.commons.logging.Log' from 'excluded.classes' but that don't seem to help.

Supplementary Issue:
When the latest (from my forked branch)  'evosuite-master-1.0.7-SNAPSHOT.jar' is used then I get a different error:

[MASTER] 00:04:02.740 [logback-2] ERROR ClientNodeImpl - Error when generating tests for: evosuite.maven.test.App with seed 1530828242516. Configuration id : null
java.lang.NullPointerException: null
        at org.evosuite.setup.ExceptionMapGenerator.handleDependency(ExceptionMapGenerator.java:29) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
        at org.evosuite.setup.ExceptionMapGenerator.handleMethodCalls(ExceptionMapGenerator.java:63) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
        at org.evosuite.setup.ExceptionMapGenerator.initializeExceptionMap(ExceptionMapGenerator.java:21) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
        at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:128) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
        at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
* Computation finished
[MASTER] 00:04:05.206 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 00:04:05.307 [main] ERROR TestGeneration - failed to write statistics data


Maybe we got some problem with the latest changes related to ExceptionMapGenerator which were pushed to solve the issue of missing exception information related to exception instrumentation.

**Comment by gofraser** [comment]
Apologies it took so long to look into this. I can generate tests for the example project attached to this issue without any problems, using the 1.0.6 release and the current HEAD. Looking at the details of the IntelliJ runconfiguration you listed, I think the problem is simply that log4j is not on the classpath. Specifically, look at your output:

```
EvoSuite
Found 1 matching classes in target D:\dev\github\evosuitemaventest\target\classes
Analyzing classpath (generating inheritance tree)
D:\dev\github\evosuitemaventest\target\classes
Current class: evosuite.maven.test.App
```

Clearly, EvoSuite was only given target/classes as classpath, but not the dependencies.  Indeed when I omit the log4j dependency, I also get a `java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager` error message. A quick way to verify this is to do:

```
mvn dependency:copy-dependencies
java -jar evosuite.jar -class evosuite.maven.test.App -projectCP target/classes/:target/dependency/log4j-api-2.10.0.jar
```

This works great.

@prathmesh-halgekar I don't get any exceptions from ExceptionMapGenerator; can you please verify if you still see this issue or whether that's something we have already fixed?

**Comment by prathmesh-halgekar** [comment]
We have fixed the NPE in commit e7a6f31. It won't throw an exception now.

**Comment by Karunyabandi** [comment]
Hi.. if classpath is set correctly means ?
