### ISSUE TITLE
org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.

### ISSUE THREAD

**Issue by AaratiT** [EvoSuite/evosuite#215]
Using maven evosuite plugin [tutorial](http://www.evosuite.org/documentation/tutorial-part-2/) 
I am trying to generate test classes.
Maven Goal used is -   evosuite:generate -Ddetail=true -Dcores=2 -DmemoryInMB=1000

### Steps to Reproduce

1. POM entries related to evosuite plugin are as follows
 ```
     <plugin>
          <groupId>org.evosuite.plugins</groupId>
          <artifactId>evosuite-maven-plugin</artifactId>
          <version>1.0.6</version>        		
</plugin>
<pluginRepositories>
       <pluginRepository>
		   <id>EvoSuite</id>
		   <name>EvoSuite Repository</name>
		   <url>http://www.evosuite.org/m2</url>
       </pluginRepository>
</pluginRepositories>
```

2. Run maven goal, as below
` evosuite:generate -Ddetail=true -Dcores=2 -DmemoryInMB=1000`
3. Evosuite plugin started the test generation, however for some the classes, no test class was  generated. (For such classes, there was WARNING message ''[MASTER] 15:11:25.730 [main] WARN  ProjectAnalyzer - Cannot initialize class: com.r.d.a.AccessFYADAOImpl" )
4. After all test generation, below exception was throws
```
org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' (http://javax.xml.XMLConstants/feature/secure-processing%27)  is not recognized.
[INFO] 	at org.apache.xerces.parsers.AbstractSAXParser.setFeature(Unknown Source)
[INFO] 	at org.apache.xerces.jaxp.SAXParserImpl.setFeatures(Unknown Source)
[INFO] 	at org.apache.xerces.jaxp.SAXParserImpl.<init>(Unknown Source)
[INFO] 	at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParserImpl(Unknown Source)
[INFO] 	at org.apache.xerces.jaxp.SAXParserFactoryImpl.setFeature(Unknown Source)
[INFO] 	at com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:121)
[INFO] 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.getXMLReader(UnmarshallerImpl.java:139)
[INFO] 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
[INFO] 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204)
[INFO] 	at org.evosuite.continuous.persistency.StorageManager.getProject(StorageManager.java:994)
[INFO] 	at org.evosuite.continuous.persistency.StorageManager.getDatabaseProject(StorageManager.java:948)
[INFO] 	at org.evosuite.continuous.persistency.StorageManager.mergeAndCommitChanges(StorageManager.java:281)
[INFO] 	at org.evosuite.continuous.ContinuousTestGeneration.execute(ContinuousTestGeneration.java:183)
[INFO] 	at org.evosuite.executionmode.Continuous.execute(Continuous.java:131)
[INFO] 	at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:266)
[INFO] 	at org.evosuite.EvoSuite.main(EvoSuite.java:302)
[INFO] [MASTER] 15:01:26.850 [main] ERROR StorageManager - Error in reading C:\workspace\MidJune_25_June\maven.1529919820679\RightsDataAccessLayer\.evosuite\project_info.xml , java.lang.IllegalStateException: org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' (http://javax.xml.XMLConstants/feature/secure-processing%27)  is not recognized.
[INFO] java.lang.IllegalStateException: org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' (http://javax.xml.XMLConstants/feature/secure-processing%27)  is not recognized.
[INFO] 	at com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:128) ~[na:1.8.0_144]
[INFO] 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.getXMLReader(UnmarshallerImpl.java:139) ~[na:1.8.0_144]
[INFO] 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157) ~[na:1.8.0_144]
[INFO] 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204) ~[na:1.8.0_144]
[INFO] 	at org.evosuite.continuous.persistency.StorageManager.getProject(StorageManager.java:994) [evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.continuous.persistency.StorageManager.getDatabaseProject(StorageManager.java:948) [evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.continuous.persistency.StorageManager.mergeAndCommitChanges(StorageManager.java:281) [evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.continuous.ContinuousTestGeneration.execute(ContinuousTestGeneration.java:183) [evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.executionmode.Continuous.execute(Continuous.java:131) [evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:266) [evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.EvoSuite.main(EvoSuite.java:302) [evosuite-master-1.0.6.jar:1.0.6]
[INFO] Caused by: org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' (http://javax.xml.XMLConstants/feature/secure-processing%27)  is not recognized.
[INFO] 	at org.apache.xerces.parsers.AbstractSAXParser.setFeature(Unknown Source) ~[xercesImpl-2.6.2.jar:na]
[INFO] 	at org.apache.xerces.jaxp.SAXParserImpl.setFeatures(Unknown Source) ~[xercesImpl-2.6.2.jar:na]
[INFO] 	at org.apache.xerces.jaxp.SAXParserImpl.<init>(Unknown Source) ~[xercesImpl-2.6.2.jar:na]
[INFO] 	at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParserImpl(Unknown Source) ~[xercesImpl-2.6.2.jar:na]
[INFO] 	at org.apache.xerces.jaxp.SAXParserFactoryImpl.setFeature(Unknown Source) ~[xercesImpl-2.6.2.jar:na]
[INFO] 	at com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:121) ~[na:1.8.0_144]
[INFO] 	... 10 common frames omitted
[INFO] [MASTER] 15:01:26.853 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1532079086852. Configuration id : null
[INFO] java.lang.RuntimeException: Error in reading C:\workspace\MidJune_25_June\maven.1529919820679\RightsDataAccessLayer\.evosuite\project_info.xml , java.lang.IllegalStateException: org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' (http://javax.xml.XMLConstants/feature/secure-processing%27)  is not recognized.
[INFO] 	at org.evosuite.continuous.persistency.StorageManager.getProject(StorageManager.java:998) ~[evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.continuous.persistency.StorageManager.getDatabaseProject(StorageManager.java:948) ~[evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.continuous.persistency.StorageManager.mergeAndCommitChanges(StorageManager.java:281) ~[evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.continuous.ContinuousTestGeneration.execute(ContinuousTestGeneration.java:183) ~[evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.executionmode.Continuous.execute(Continuous.java:131) ~[evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:266) ~[evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.EvoSuite.main(EvoSuite.java:302) ~[evosuite-master-1.0.6.jar:1.0.6]
[ERROR] Error in EvoSuite
[INFO] Stopping spawn process manager
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28:08 min
[INFO] Finished at: 2018-07-20T15:01:27+05:30
[INFO] Final Memory: 15M/37M
[INFO] ------------------------------------------------------------------------ 

```
 

### EvoSuite Arguments
-Ddetail=true -Dcores=2 -DmemoryInMB=1000

### Current Result
As stated earlier, for some of the classes, the test class was generated
And when evosuite could not generate the test class, below warning message was given

[MASTER] 15:11:25.730 [main] WARN  ProjectAnalyzer - Cannot initialize class: com.r.d.a.AccessFYADAOImpl

### Expected result
1. In case of partial test generation, the classes for which a test class was generated, should have been part of "best-test" folder.
So that during maven export goal, those class files will be copied to 'target' folder.
Suppose there are 50 classes in project , and evosuite has generated test classes for 20, then those 20 should be able to export using maven export 
2.The test classes should get generated with summary in csv or HTML format

### Additional info
1.  We observed that, when evosuite generate test classes for all classes in given maven project, the above exception is not thrown. So this behavior is observed only during partial test generation.
2. The classes for which evosuite could not generate test classes, we observed that such classes are  using a customer logger library. 
If we comment the logger related code, then test class is generated. However we want to know the exact reason & work around (which is other than commenting the logger code) to solve this problem.

**Comment by gofraser** [comment]
I haven't seen this before, but some googling suggests you've got an old/conflicting version of xerces on your classpath (e.g. https://stackoverflow.com/questions/32261771/saxnotrecognizedexception-feature-http-javax-xml-xmlconstants-feature-secure). How does your pom.xml look like, are there other dependencies/settings? You only showed the excerpt that involves EvoSuite.
