### ISSUE TITLE
Evosuite test execution error org.evosuite.runtime.mock.java.lang.MockThrowable cannot be cast to oracle.net.ns.NetException

### ISSUE THREAD

**Issue by AaratiT** [EvoSuite/evosuite#217]
### Context
This is in continuation with my earlier thread [https://github.com/EvoSuite/evosuite/issues/213](https://github.com/EvoSuite/evosuite/issues/213)
Added few more methods to ascertain whether evosuite connects with Oracle database to execute particular method or not.

### Steps to Reproduce
1. Used maven plugin to generate test classes
2.  Export  generated  into "test" folder using  evosuite:export
3. Used below command to run the test
java  -cp  ".\log4j-1.2.17.jar;.\ojdbc6-11.2.0.3.jar;.\xdb-1.0.jar;.\hsqldb-2.4.0.jar;.\commons-codec-1.3.jar;.\slf4j-log4j12-1.7.16.jar;.\slf4j-api-1.7.16.jar;\target\classes;.\evosuite-standalone-runtime-1.0.6.jar;.\junit-4.12.jar;.\hamcrest-core-1.3.jar;"   org.junit.runner.JUnitCore  t.c.u.g.KeyClient_ESTest

### Current Result
java.lang.AssertionError: Exception was not thrown in c.u.g.KeyClient but in oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:359): java.lang.ClassCastException: org.evosuite.runtime.mock.java.lang.MockThrowable cannot be cast to oracle.net.ns.NetException
        at org.evosuite.runtime.EvoAssertions.assertThrownBy(EvoAssertions.java:112)
        at org.evosuite.runtime.EvoAssertions.verifyException(EvoAssertions.java:49)
        at test.c.u.g.KeyClient_ESTest.test4(KeyClient_ESTest.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:745)
2) test1(test.c.u.g.KeyClient_ESTest)
java.lang.AssertionError: Exception was not thrown in c.u.g.KeyClient but in oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:359): java.lang.ClassCastException: org.evosuite.runtime.mock.java.lang.MockThrowable cannot be cast to oracle.net.ns.NetException
        at org.evosuite.runtime.EvoAssertions.assertThrownBy(EvoAssertions.java:112)
        at org.evosuite.runtime.EvoAssertions.verifyException(EvoAssertions.java:49)
        at test.c.u.g.KeyClient_ESTest.test1(KeyClient_ESTest.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:745)

FAILURES!!!
Tests run: 6,  Failures: 2

 
 
### Expected result
1. Test case execution must connect to database , execute select query & return the result
2. Test to be paseed

### Additional info
1.  In log4j log files, there are evosuite class loader error
example
EvoClassLoader:122 - Error while loading class: java.lang.ClassNotFoundException: Class 'oracle/security/pki/OraclePKIProvider.class' should be in target project, but could not be found!
Error while loading class: java.lang.ClassNotFoundException: Class 'com/ibm/uvm/tools/DebugSupport.class' should be in target project, but could not be found!
etc
I don't think  the above class loader errors could be an issues as some of the test have successfully executed. 
2. Additionally , if I create simple Junit Test & run it in eclipse or using command prompt. It is successfully executed ie. it generates desired output
command used is` org.junit.runner.JUnitCore  test.c.u.g.A `

```
public class A {

	@Test
	public final void testGetInstance() {
		fail("Not yet implemented"); // TODO
	}

	@Test
	public final void testGetKey() {
		KeyClient.getKey();
		
	}

```

Thank you.

**Comment by AaratiT** [comment]
After marking below Evosuiteparameters as **false**, the test ran with desired results.
```
@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = false, useVFS = false, useVNET = false, resetStaticState = true, separateClassLoader =false, useJEE = true) 
public class KeyClient_ESTest extends KeyClient_ESTest_scaffolding {
@Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EvoSuiteRemoteAddress evoSuiteRemoteAddress0 = new EvoSuiteRemoteAddress("10.40.16.171", 1521);
      NetworkHandling.openRemoteTcpServer(evoSuiteRemoteAddress0);
      // Undeclared exception!
      try { 
        KeyClient.testKey();
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
         //
         // SQL Error! Check output console
         //
         verifyException("c.u.g.KeyClient", e);
      }
     
  }
```
However there still gives result as  failed, even though the code inside test is successfully executed

```
java.lang.AssertionError: Expecting exception: RuntimeException
        at org.junit.Assert.fail(Assert.java:88)
        at test.c.u.g.KeyClient_ESTest.test0(KeyClient_ESTest.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:745)
```
Once I comment below line, the test run is successful
` fail("Expecting exception: RuntimeException");`

So now I have below questions:
1. What is significance of below parameters ?
mockJVMNonDeterminism , useVFS , useVNET , separateClassLoader 

2. Evosuite on test generation adds,  below line in test method.
Shouldn't it be part of catch block, when the test fails.
fail("Expecting exception: RuntimeException");

**Comment by gofraser** [comment]
If you set `useVNET=false`, then EvoSuite will not use it's own mocked network interface. In this case, the behaviour of the tested code is different to what EvoSuite observed during test generation (the EvoSuiteRemoteAddress will not be used by the class under test), and the RuntimeException doesn't happen. This is why the `fail` is triggered. Commenting it out makes the test quite useless, I think.

The original problem reported at the beginning of this issue is that a **different** exception was observed at runtime, thrown at a different place in the code. I would need some way to reproduce this problem to say anything about it -- ideally, a minimised class/project and the exact commandline to reproduce the problem.

Finally, the messages that "XYZ should be in target project, but could not be found" mean exactly what it says -- there are some dependency classes that are not on the classpath. This usually suggests that you did not correctly specify all the dependencies. (Which may or may not influence the original issue reported).
