### ISSUE TITLE
org.evosuite.testcase.TestChromosome cannot be cast to org.evosuite.testsuite.TestSuiteChromosome

### ISSUE THREAD

**Issue by sr1993** [EvoSuite/evosuite#219]
### Context
When I use the executable evosuite-1.0.6.jar and the current master branch project to generate test cases for a class by MOSA, this 
'org.evosuite.testcase.TestChromosome cannot be cast to org.evosuite.testsuite.TestSuiteChromosome' happens. 
the command line is : 
java -jar evosuite.jar -target d:\test -Dcriterion=branch -base_dir=d:\test -generateMOSuite
When I use '-generateTests', the above error also happens. The option '-generateSuite' works well.

The following information also shows:
* Computation finished
[MASTER] 19:20:53.395 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 19:20:53.496 [main] ERROR TestGeneration - failed to write statistics data

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1. There is a class file A.class in directory "d:\test". Its source code is as follows:
<pre><code>
public class A {
	public static void t(int flag, int x, int y , int z){
		if(x > 3){
			z = z + 1;
		}
		else{
			x = flag;
		}
		if(y == 4){
			z = y + 1;
		}else{
			x = 1;
		}
		
		if(x < 2){
			z = z/2;
		}
		else{
			y -= 5;
		}
		z = y + x - z;
		if( y > 0){
			z = x + y;
		}
		else{
			z -= 1;
		}
		System.out.println(z);
	}
}
</code></pre>
2. Use command line: java -jar evosuite.jar -target d:\test -Dcriterion=branch -base_dir=d:\test -generateMOSuite

### EvoSuite Arguments

-target d:\test -Dcriterion=branch -base_dir=d:\test -generateMOSuite 
or -target d:\test -Dcriterion=branch -base_dir=d:\test -generateTests

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]
[MASTER] 16:43:36.556 [logback-2] ERROR ClientNodeImpl - Error when generating tests for: A with seed 1533199414462. Configuration id : null
java.lang.ClassCastException: org.evosuite.testcase.TestChromosome cannot be cast to org.evosuite.testsuite.TestSuiteChromosome
	at org.evosuite.ga.archive.CoverageArchive.mergeArchiveAndSolution(CoverageArchive.java:259) ~[classes/:na]
	at org.evosuite.ga.archive.CoverageArchive.mergeArchiveAndSolution(CoverageArchive.java:1) ~[classes/:na]
	at org.evosuite.ga.metaheuristics.GeneticAlgorithm.updateBestIndividualFromArchive(GeneticAlgorithm.java:1040) ~[classes/:na]
	at org.evosuite.TimeController.execute(TimeController.java:112) ~[classes/:na]
	at org.evosuite.ga.metaheuristics.MonotonicGA.generateSolution(MonotonicGA.java:315) ~[classes/:na]
	at org.evosuite.strategy.IndividualTestStrategy.generateTests(IndividualTestStrategy.java:182) ~[classes/:na]
	at org.evosuite.TestSuiteGenerator.generateTests(TestSuiteGenerator.java:653) ~[classes/:na]
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:236) ~[classes/:na]
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_181]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_181]

**Comment by gofraser** [comment]
It seems that the issue in the CoverageArchive has been fixed.  However, using `-generateMOSuite` still causes a similar issue:

```
[MASTER] 15:43:42.815 [logback-2] ERROR ClientNodeImpl - Error when generating tests for: A with seed 1536500621651. Configuration id : null
java.lang.ClassCastException: org.evosuite.testcase.TestChromosome cannot be cast to org.evosuite.testsuite.TestSuiteChromosome
	at org.evosuite.ProgressMonitor.fitnessEvaluation(ProgressMonitor.java:129) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.ga.metaheuristics.GeneticAlgorithm.notifyEvaluation(GeneticAlgorithm.java:909) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
```

@jose I assume this is because `-generateMOSuite` really requires that the algorithm is set to MOSA. Shouldn't this actually be done automatically, rather than requiring `-Dalgorithm=MOSA`?
