### ISSUE TITLE
Exception class java.lang.reflect.InvocationTargetException: null , cause class com.sun.tools.attach.AttachNotSupportedException no providers installed

### ISSUE THREAD

**Issue by SeraphicRav** [EvoSuite/evosuite#23]
Hi !

I could generate the code for the tests just right using "mvn compile -Dcores=2 evosuite:generate evosuite:export" but when I run "mvn test" I get an error everywhere for each test class. The tested class use CDI injections, I do not know if it is revelant.

Here is a sample of the test error logs :
[evosuite.error.log.txt](https://github.com/EvoSuite/evosuite/files/225589/evosuite.error.log.txt)

Can someone tell me what is wrong please ?

Best regards

**Comment by arcuri82** [comment]
Hi,
  CDI should not be the problem here (btw, it is not supported now in 1.0.3, but it will be in the next release). It seems an issue with the Java Agent, but that should be off by default (see http://www.evosuite.org/documentation/measuring-code-coverage and https://github.com/EvoSuite/evosuite/issues/22). Are you using some extra special settings? which version of EvoSuite, JDK and OS are you using?

cheers

Andrea

**Comment by SeraphicRav** [comment]
Hi !

Ok for CDI.

I am still on version 1.0.2, with Oracle JDK 1.8.0_05 on  Windows 7 Enterprise.

I have no special setting, the annotations of each test class are the following :
@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 

Best regards

**Comment by arcuri82** [comment]
it looks like a problems with Java Agent on Windows. However, that default has been changed in 1.0.3. Can you try with 1.0.3 and see if you still have such issue?

**Comment by SeraphicRav** [comment]
Hi !

The error changed. I mostly have this kind of error (we did not use powermock in the project before evosuite) :
`initializationError(fr.chicken.AjustementServiceTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.ClassCastException: org.powermock.modules.junit4.internal.impl.PowerMockJUnit49RunnerDelegateImpl cannot be cast to org.powermock.modules.junit4.common.internal.PowerMockJUnitRunnerDelegate
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:143)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:39)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:217)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:59)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:33)
	at sun.reflect.GeneratedConstructorAccessor63.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
`

**Comment by arcuri82** [comment]
Hi

EvoSuite does not use PowerMock. And in that log, I do not see any reference to EvoSuite. Is this problem related to EvoSuite? If you remove the EvoSuite generated tests, do you still have that issue? (I guess that could happen if somehow the execution of EvoSuite tests would mess up with some JUnit internal stuff...)

**Comment by arcuri82** [comment]
Hi,
  I made an alpha release (still few things to fix and more testing before a proper / official release) where this issue should had been fixed. Version is 1.0.4-alpha1, on Maven Central (http://search.maven.org/#search%7Cga%7C1%7Cevosuite). If you use an executable jar instead of Maven, download the one from http://repo1.maven.org/maven2/org/evosuite/evosuite-master/1.0.4-alpha1/

can you confirm whether the issue you reported has been solved or not?  

cheers

Andrea

**Comment by SeraphicRav** [comment]
Hi !

I launched the test generation, I am waiting fot it to end and launch the tests. I will keep you updated.

Best regards !

**Comment by SeraphicRav** [comment]
Hi have no exception anymore, everything works fine ! Thanks !
