### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: null on generating testcases using EvoSuite

### ISSUE THREAD

**Issue by anujgupta160189** [EvoSuite/evosuite#246]
### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1.Getting Illegal Argument Exception while generating testcases on a class.

### EvoSuite Arguments
Below are the logs printed on std output:

Going to execute command:
**/opt/apache-maven-3.6.0/bin/mvn  compile  evosuite:generate  -Dcores=4  -DmemoryInMB=8000  -DtimeInMinutesPerClass=1  -DspawnManagerPort=54965  -Dcuts=com.mmt.cb.connector.DatabaseConnector  evosuite:export  -DtargetFolder=src/test/java/evo  
in folder: /Users/mmt5776/Documents/git/common-client-backend/HCS-Common-Backend**
Going to execute command:
/opt/apache-maven-3.6.0/bin/mvn  compile  evosuite:generate  -Dcores=4  -DmemoryInMB=8000  -DtimeInMinutesPerClass=1  -DspawnManagerPort=54965  -Dcuts=com.mmt.cb.connector.DatabaseConnector  evosuite:export  -DtargetFolder=src/test/java/evo  
in folder: /Users/mmt5776/Documents/git/common-client-backend/HCS-Common-Backend
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.mmt.common-backend:common-backend:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.jacoco:jacoco-maven-plugin @ line 353, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ---------------< com.mmt.common-backend:common-backend >----------------
[INFO] Building Common Backend 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ common-backend ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] Copying 13 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ common-backend ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] >>> evosuite-maven-plugin:1.0.6:generate (default-cli) > compile @ common-backend >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ common-backend ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] Copying 13 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ common-backend ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< evosuite-maven-plugin:1.0.6:generate (default-cli) < compile @ common-backend <<<
[INFO] 
[INFO] 
[INFO] --- evosuite-maven-plugin:1.0.6:generate (default-cli) @ common-backend ---
[INFO] Going to generate tests with EvoSuite
[INFO] Total memory: 8000mb
[INFO] Time per class: 1 minutes
[INFO] Number of used cores: 4
[INFO] Specified classes under test: com.mmt.cb.connector.DatabaseConnector
[INFO] Target: /Users/mmt5776/Documents/git/common-client-backend/HCS-Common-Backend/target/classes
[INFO] Basedir: /Users/mmt5776/Documents/git/common-client-backend/HCS-Common-Backend
[INFO] SLF4J: Class path contains multiple SLF4J bindings.
[INFO] SLF4J: Found binding in [jar:file:/Users/mmt5776/.m2/repository/org/evosuite/evosuite-master/1.0.6/evosuite-master-1.0.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[INFO] SLF4J: Found binding in [jar:file:/Users/mmt5776/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[INFO] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[INFO] SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[INFO] * EvoSuite 1.0.6
[INFO] Going to execute 1 jobs
[INFO] Estimated completion time: 1 minutes, by 2019-01-11T19:33:34.513
[INFO] Going to start job for: com.mmt.cb.connector.DatabaseConnector. Expected to end in 60 seconds, by 2019-01-11T19:33:34.535
[INFO] Completed job. Left: 0
[INFO] * Updating database to com.mmt.cb.connector.DatabaseConnector
[INFO] === CTG run results ===
[INFO] Removed test suites: 0
[INFO] New test suites: 0
[INFO] WARN: failed to generate tests for com.mmt.cb.connector.DatabaseConnector
[INFO] 
[INFO] --- evosuite-maven-plugin:1.0.6:export (default-cli) @ common-backend ---
[INFO] Exporting tests
[INFO] Nothing to export
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.362 s
[INFO] Finished at: 2019-01-11T19:32:37+05:30
[INFO] ------------------------------------------------------------------------

### Current Result
****Client Std Error logs**** 
[MASTER] 19:27:18.932 [pool-2-thread-1] ERROR TestSuiteGenerator - Problem for com.mmt.cb.connector.DatabaseConnector. Full stack:
java.lang.ClassNotFoundException: null
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:201)
	at org.evosuite.instrumentation.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:168)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
	at org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
	at org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
	at org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
	at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
	at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at org.objectweb.asm.commons.SerialVersionUIDAdder.<init>(SerialVersionUIDAdder.java:190)
	at org.objectweb.asm.commons.SerialVersionUIDAdder.<init>(SerialVersionUIDAdder.java:173)
	at org.evosuite.instrumentation.BytecodeInstrumentation.transformBytes(BytecodeInstrumentation.java:248)
	at org.evosuite.instrumentation.InstrumentingClassLoader.getTransformedBytes(InstrumentingClassLoader.java:175)
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:192)
	... 17 common frames omitted

 
 
Any pointers if anyone can help it would be great.

**Comment by alexmnyc** [comment]
same here

**Comment by alexmnyc** [comment]
```
java -jar evosuite-1.0.6.jar  -generateTests  -prefix com.mypackage -projectCP $(echo "lib"/*.jar | tr ' ' ':'):build/classes/java/main

[MASTER] 20:50:56.429 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1582595456422. Configuration id : null
java.lang.IllegalArgumentException: null
	at org.evosuite.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:160) ~[evosuite-1.0.6.jar:1.0.6]
	at org.evosuite.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:143) ~[evosuite-1.0.6.jar:1.0.6]
	at org.evosuite.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:418) ~[evosuite-1.0.6.jar:1.0.6]
	at org.evosuite.setup.InheritanceTreeGenerator.analyzeClassStream(InheritanceTreeGenerator.java:238) ~[evosuite-1.0.6.jar:1.0.6]
	at org.evosuite.setup.InheritanceTreeGenerator.createFromClassPath(InheritanceTreeGenerator.java:101) ~[evosuite-1.0.6.jar:1.0.6]
	at org.evosuite.EvoSuite.generateInheritanceTree(EvoSuite.java:90) ~[evosuite-1.0.6.jar:1.0.6]
	at org.evosuite.executionmode.TestGeneration.generateTestsPrefix(TestGeneration.java:173) ~[evosuite-1.0.6.jar:1.0.6]
	at org.evosuite.executionmode.TestGeneration.executeTestGeneration(TestGeneration.java:81) ~[evosuite-1.0.6.jar:1.0.6]
	at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:269) ~[evosuite-1.0.6.jar:1.0.6]
	at org.evosuite.EvoSuite.main(EvoSuite.java:302) ~[evosuite-1.0.6.jar:1.0.6]
```

**Comment by wzd585426** [comment]
解决了吗，我也碰到同样的问题了

**Comment by dongyan8912** [comment]
Is  it resolved now? I have the same problem using 1.0.6.

[MASTER] 11:35:15.415 [pool-2-thread-1] ERROR TestSuiteGenerator - Problem for com.huami.effective.utils.HttpClientUtils. Full stack:
java.lang.IllegalArgumentException: null
	at org.evosuite.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
	at org.evosuite.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
	at org.evosuite.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
	at org.evosuite.setup.InheritanceTreeGenerator.analyzeClassStream(InheritanceTreeGenerator.java:238)
	at org.evosuite.setup.InheritanceTreeGenerator.createFromClassPath(InheritanceTreeGenerator.java:101)
	at org.evosuite.setup.DependencyAnalysis.initInheritanceTree(DependencyAnalysis.java:77)
	at org.evosuite.setup.DependencyAnalysis.analyzeClass(DependencyAnalysis.java:131)
	at org.evosuite.TestSuiteGenerator.initializeTargetClass(TestSuiteGenerator.java:110)
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:130)
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jiseongg** [comment]
Same here, I've written scripts reproducing this error. All code block here can be executed with copy-and-paste. I suppose that `-prefix` option has a problem. I found it when investigating the [Tutorial_Experiments](https://www.evosuite.org/documentation/tutorial-part-3/)

## Platform Information
- cat /etc/issue
```
Ubuntu 18.04.5 LTS
```
- java -version
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```
- mvn -version
```
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_292, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-135-generic", arch: "amd64", family: "unix"
```

## Reproducing errors
1. Install EVOSUITE
```
# install evosuite
git clone https://github.com/evosuite/evosuite
cd evosuite
mvn clean install -DskipTests -DskipITs
```
2. Download tutorials
```
# download tutorial
wget https://evosuite.org/files/tutorial/Tutorial_Experiments.zip
unzip Tutorial_Experiments.zip

# Change evosuite-plugins version from 1.0.3 to 1.0.6 in pom.xml
```
Here, I've changed the version of **evosuite-standalone-runtime** and **evosuite-maven-plugin** in **pom.xml** file from `1.0.3` to `1.0.6`, since there is a build failure with `1.0.3`.

3. Run EVOSUITE

In this step, there is a branch for two cases, one occurring errors and the other without errors. For the command, I've followed the instruction in the section **Running an experiment** of [Tutorial_Experiments](https://www.evosuite.org/documentation/tutorial-part-3/)
First one:
```
export EVOSUITE="java -jar $HOME/.m2/repository/org/evosuite/evosuite-master/1.1.1-SNAPSHOT/evosuite-master-1.1.1-SNAPSHOT.jar"

cd Tutorial_Experiments
$EVOSUITE -setup target/classes target/dependency/commons-collections-3.2.2.jar

# this does not work
$EVOSUITE -criterion branch -prefix tutorial -Doutput_variables=TARGET_CLASS,criterion,Size,Length,MutationScore
```
The output of the first case is like below

> \* EvoSuite 1.1.1-SNAPSHOT
> \* Creating new evosuite.properties in /home/vagrant/Tutorial_Experiments/evosuite-files
> \* Classpath: target/classes:target/dependency/commons-collections-3.2.2.jar
> \* EvoSuite 1.1.1-SNAPSHOT
> \* Analyzing classpath (generating inheritance tree)
>   \- target/classes
>   \- target/dependency/commons-collections-3.2.2.jar
> \* Found 9 matching classes for prefix tutorial
> \* Current class: tutorial.Bank
>  ...
> \* Computation finished
> [MASTER] 07:07:40.016 [logback-2] ERROR ClientNodeImpl - Error when generating tests for: tutorial.Bank with seed 1627974458963. Configuration id : null
> java.lang.IllegalArgumentException: Unsupported type of fitness function: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness
> 	at org.evosuite.ga.metaheuristics.TestSuiteAdapter.mapFitnessFunctionToTestCaseLevel(TestSuiteAdapter.java:646)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
> 	at org.evosuite.ga.metaheuristics.TestSuiteAdapter.addFitnessFunctions(TestSuiteAdapter.java:653)
> 	at org.evosuite.strategy.WholeTestSuiteStrategy.generateTests(WholeTestSuiteStrategy.java:67)
> 	at org.evosuite.TestSuiteGenerator.generateTests(TestSuiteGenerator.java:642)
> 	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:220)
> 	at org.evosuite.rmi.service.ClientNodeImpl.lambda$startNewSearch$0(ClientNodeImpl.java:150)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> [MASTER] 07:07:40.130 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
> [MASTER] 07:07:40.263 [main] ERROR TestGeneration - failed to write statistics data
> ...

However, if I run without `-prefix` option, manually specifying each class name, it works correctly. Here is this second case:
```
export EVOSUITE="java -jar $HOME/.m2/repository/org/evosuite/evosuite-master/1.1.1-SNAPSHOT/evosuite-master-1.1.1-SNAPSHOT.jar"

cd Tutorial_Experiments
$EVOSUITE -setup target/classes target/dependency/commons-collections-3.2.2.jar

# this works
$EVOSUITE -criterion branch -class tutorial.ATM -Doutput_variables=TARGET_CLASS,criterion,Size,Length,MutationScore
$EVOSUITE -criterion branch -class tutorial.ATMCard -Doutput_variables=TARGET_CLASS,criterion,Size,Length,MutationScore
$EVOSUITE -criterion branch -class tutorial.Bank -Doutput_variables=TARGET_CLASS,criterion,Size,Length,MutationScore
$EVOSUITE -criterion branch -class tutorial.BankAccount -Doutput_variables=TARGET_CLASS,criterion,Size,Length,MutationScore
$EVOSUITE -criterion branch -class tutorial.Owner -Doutput_variables=TARGET_CLASS,criterion,Size,Length,MutationScore
$EVOSUITE -criterion branch -class tutorial.CurrentAccount -Doutput_variables=TARGET_CLASS,criterion,Size,Length,MutationScore
$EVOSUITE -criterion branch -class tutorial.SavingsAccount -Doutput_variables=TARGET_CLASS,criterion,Size,Length,MutationScore
$EVOSUITE -criterion branch -class tutorial.Company -Doutput_variables=TARGET_CLASS,criterion,Size,Length,MutationScore
$EVOSUITE -criterion branch -class tutorial.Person -Doutput_variables=TARGET_CLASS,criterion,Size,Length,MutationScore
```
The output is normal like below

> \* EvoSuite 1.1.1-SNAPSHOT
> \* Creating new evosuite.properties in /home/vagrant/Tutorial_Experiments/evosuite-files
> \* Classpath: target/classes:target/dependency/commons-collections-3.2.2.jar
> \* EvoSuite 1.1.1-SNAPSHOT
> \* Going to generate test cases for class: tutorial.ATM
> \* Starting Client-0
> \* Properties loaded from /home/vagrant/Tutorial_Experiments/evosuite-files/evosuite.properties
> \* Connecting to master process on port 4635
> \* Analyzing classpath:
>   \- target/classes
>   \- target/dependency/commons-collections-3.2.2.jar
> \* Finished analyzing classpath
> \* Generating tests for class tutorial.ATM
> \* Test criterion:
>   \- Branch Coverage
> \* Total number of test goals for DYNAMOSA: 20
> \* Using seed 1627973535788
> [Progress:>                             0%] [Cov:>                                  0%]* Starting evolution
> \* Initial Number of Goals in DynaMOSA = 10 / 20
> [Progress:>                             1%] [Cov:===================================100%]
> \* Search finished after 2s and 8 generations, 10671 statements, best individual has fitness: 0.0
> \* Minimizing test suite
> \* Going to analyze the coverage criteria
> ...
> \*Writing tests to file
> \* Writing JUnit test case 'ATM_ESTest' to evosuite-tests
> \* Done!
> 
> \* Computation finished
> ... (success for all classes)

Thus, I think there is an error in processing `-prefix` option.

**Comment by jiseongg** [comment]
I think it is due to malfunction of `-prefix` option. I've made new issue about this recently. #372
