### ISSUE TITLE
 How can I make it work in a OSGI program?

### ISSUE THREAD

**Issue by MyGitForWF** [EvoSuite/evosuite#290]
My program is based on OSGI, and I want to use it to build test cases for my program. I see that the latest submission contains content for osgi. I tried to build the plugin and runtime by myself using the latest source code.
When I didn't skip the test, I failed. By skipping the test, I built successfully.
But when I finally used it, something went wrong
it‘s std_err_MASTER.log：
java.lang.NullPointerException: null
	at org.evosuite.executionmode.TestGeneration.generateTests(TestGeneration.java:501) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.executionmode.TestGeneration.executeTestGeneration(TestGeneration.java:80) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:352) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.EvoSuite.main(EvoSuite.java:117) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]

**Comment by MyGitForWF** [comment]
mvn compile -DmemoryInMB=2000 -Dcores=2 -DtargetFolder=src/test/java evosuite:generate evosuite:export
