### ISSUE TITLE
TestSuiteGenerator fail

### ISSUE THREAD

**Issue by wzd585426** [EvoSuite/evosuite#297]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

[MASTER] 16:36:08.729 [pool-2-thread-1] ERROR TestSuiteGenerator - Problem for com.yss.cache.HDayCache. Full stack:
java.lang.IllegalArgumentException: null
	at org.evosuite.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:160) ~[evosuite-standalone-runtime-1.0.6.jar:1.0.6]
	at org.evosuite.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:143) ~[evosuite-standalone-runtime-1.0.6.jar:1.0.6]
	at org.evosuite.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:418) ~[evosuite-standalone-runtime-1.0.6.jar:1.0.6]
	at org.evosuite.setup.InheritanceTreeGenerator.analyzeClassStream(InheritanceTreeGenerator.java:238) ~[evosuite-master-1.0.6.jar:1.0.6]
	at org.evosuite.setup.InheritanceTreeGenerator.createFromClassPath(InheritanceTreeGenerator.java:101) ~[evosuite-master-1.0.6.jar:1.0.6]
	at org.evosuite.setup.DependencyAnalysis.initInheritanceTree(DependencyAnalysis.java:77) ~[evosuite-master-1.0.6.jar:1.0.6]
	at org.evosuite.setup.DependencyAnalysis.analyzeClass(DependencyAnalysis.java:131) ~[evosuite-master-1.0.6.jar:1.0.6]
	at org.evosuite.TestSuiteGenerator.initializeTargetClass(TestSuiteGenerator.java:110) ~[evosuite-master-1.0.6.jar:1.0.6]
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:130) ~[evosuite-master-1.0.6.jar:1.0.6]
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) [evosuite-master-1.0.6.jar:1.0.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_221]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1.after mvn compile success, mvn evosuite:generate fail
2.
3.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

### Additional info
*Please add any information of interest here below*

**Comment by jose** [comment]
Hi @wzd585426,

A number of issues and improvements have been made since we release version 1.0.6. Could you please try to use the latest version of EvoSuite (i.e., the one from the master branch) and let us know whether you still get that `java.lang.IllegalArgumentException` when you run EvoSuite on `com.yss.cache.HDayCache`? If the problem persists, could you please share the project under test with me so that I can debug this issue?


--
Best,
Jose

**Comment by rahul208in** [comment]
i am getting same error in 1.0.6... any idea why? on mvn command i get below msg

Registered remote process from /127.0.0.1:57355
Registered remote process from /127.0.0.1:57361
completed job. Left: 0
* Updating database to com.XXX.XXX.XXX 
=== CTG run results ===
Removed test suites : 0
New test suites: 0
WARN: failed to generate tests for com.XXX.XXX.XXX
stopping spawn process manager


i am using windows maven command \
mvn compile -Dcuts=com.XXX.XXX.XXX -DtargerFolder=src/test/java/evosuite evosuite:generate evosuite:export -Ddetail=true

please assist. Thanks

**Comment by shuqing1** [comment]
请问你是怎么解决这个问题的？
