### ISSUE TITLE
java.lang.ClassCastException: org.evosuite.testcase.TestChromosome cannot be cast to org.evosuite.testsuite.TestSuiteChromosome

### ISSUE THREAD

**Issue by jmath675** [EvoSuite/evosuite#308]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*
I am using Evosuite with the following Java Project
[doop.zip](https://github.com/EvoSuite/evosuite/files/5202823/doop.zip)

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1. Unzip doop.zip
2. Run "java -jar evosuite.jar -listClasses -target C:\PATH\TO\doop" and you will see that the classes are visible to evosuite
3. Run "java -jar evosuite.jar -generateTests -class doopProj2.doopClass3 -projectCP C:\PATH\TO\doop\doopProj2\bin"

### Current Result

* EvoSuite 1.0.6
* Going to generate test cases for class: doopProj2.doopClass3
* Starting client
* Connecting to master process on port 17041
* Analyzing classpath:
  - C:\Users\M60459\eclipse-workspace\doopProj2\bin
[MASTER] 11:22:16.284 [logback-1] WARN  CheapPurityAnalyzer - doop2.doopClass2 was not found in the inheritance tree. Using DEFAULT value for cheap-purity analysis
[MASTER] 11:22:16.284 [logback-1] WARN  InheritanceTree - Class not in inheritance graph: doop2.doopClass2
* Finished analyzing classpath
* Generating tests for class doopProj2.doopClass3
* Test criteria:
  - Line Coverage
  - Branch Coverage
  - Exception
  - Mutation testing (weak)
  - Method-Output Coverage
  - Top-Level Method Coverage
  - No-Exception Top-Level Method Coverage
  - Context Branch Coverage
* Setting up search algorithm for individual test generation
* Total number of test goals:
  - Line 5
  - Branch 2
  - Exception 0
  - MutationFactory 4
  - Output 0
  - Method 2
  - MethodNoException 2
  - CBranchFitnessFactory 2
* Total number of test goals: 17
* Budget: 60
[MASTER] 11:22:16.564 [RMI TCP Connection(2)-127.0.0.1] WARN  SearchStatistics - searchStatistics expected a TestSuiteChromosome
[MASTER] 11:23:17.347 [logback-2] ERROR ClientNodeImpl - Error when generating tests for: doopProj2.doopClass3 with seed 1599751335115. Configuration id : null
java.lang.ClassCastException: org.evosuite.testcase.TestChromosome cannot be cast to org.evosuite.testsuite.TestSuiteChromosome
        at org.evosuite.ga.archive.CoverageArchive.mergeArchiveAndSolution(CoverageArchive.java:259) ~[evosuite.jar:1.0.6]
        at org.evosuite.ga.archive.CoverageArchive.mergeArchiveAndSolution(CoverageArchive.java:43) ~[evosuite.jar:1.0.6]
        at org.evosuite.ga.metaheuristics.GeneticAlgorithm.updateBestIndividualFromArchive(GeneticAlgorithm.java:1040) ~[evosuite.jar:1.0.6]
        at org.evosuite.TimeController.execute(TimeController.java:112) ~[evosuite.jar:1.0.6]
        at org.evosuite.ga.metaheuristics.MonotonicGA.generateSolution(MonotonicGA.java:315) ~[evosuite.jar:1.0.6]
        at org.evosuite.strategy.IndividualTestStrategy.generateTests(IndividualTestStrategy.java:182) ~[evosuite.jar:1.0.6]
        at org.evosuite.TestSuiteGenerator.generateTests(TestSuiteGenerator.java:653) ~[evosuite.jar:1.0.6]
        at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:236) ~[evosuite.jar:1.0.6]
        at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) ~[evosuite.jar:1.0.6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
* Computation finished

**Comment by apanichella** [comment]
Try with the setting:
`java -jar evosuite.jar -generatMOSuite -Dalgorithm=DYNAMOSA -class doopProj2.doopClass3 -projectCP C:\PATH\TO\doop\doopProj2\bin`
or 
`java -jar evosuite.jar -generatSuite -class doopProj2.doopClass3 -projectCP C:\PATH\TO\doop\doopProj2\bin`
