### ISSUE TITLE
NPE on NetworkInterfaceState.getMacAddr

### ISSUE THREAD

**Issue by greenlaw110** [EvoSuite/evosuite#31]
I keep getting this exception when running the unit test cases generated by EvoSuite:

```
May 31, 2016 12:21:12 AM org.bson.types.ObjectId createMachineIdentifier
WARNING: Failed to get machine identifier from network interface, using random number instead
java.lang.NullPointerException
	at org.evosuite.runtime.vnet.NetworkInterfaceState.getMacAddr(NetworkInterfaceState.java:105)
	at org.evosuite.runtime.mock.java.net.MockNetworkInterface.getHardwareAddress(MockNetworkInterface.java:126)
	at org.bson.types.ObjectId.createMachineIdentifier(ObjectId.java:475)
	at org.bson.types.ObjectId.__STATIC_RESET(ObjectId.java:459)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.evosuite.runtime.classhandling.ClassResetter.reset(ClassResetter.java:159)
	at org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(ClassStateSupport.java:108)
	at com.pixolut.connectable.sys.FrontEndError_ESTest_scaffolding.resetClasses(FrontEndError_ESTest_scaffolding.java:579)
	at com.pixolut.connectable.sys.FrontEndError_ESTest_scaffolding.doneWithTestCase(FrontEndError_ESTest_scaffolding.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
```

The debug info

![image](https://cloud.githubusercontent.com/assets/216930/15660048/3fe6c2e4-2719-11e6-9e27-387d61b2a0bc.png)

**Comment by arcuri82** [comment]
thanks for reporting it. It was a silly NPE bug, whose fix is now in the latest Git commit, and will be part of the next EvoSuite release (hopefully sometime during June...)
