### ISSUE TITLE
Exceptions when runing PITEST on test cases generated by Evosuite

### ISSUE THREAD

**Issue by justinwm** [EvoSuite/evosuite#35]
Hi Everyone!

I am currently running PiTest on the JUnit test cases generated by Evosuite. 
I have included _evosuite-standalone-runtime.jar_ as said in the documentations.

I looked at the log information generated by Evosuite and found the following:

`8:22:11 PM PIT >> INFO : MINION : 264 [main] INFO org.evosuite.runtime.instrumentation.EvoClassLoader - Seeing class for first time: org.pitest.junit.adapter.ForeignClassLoaderCustomRunnerExecutor

8:22:11 PM PIT >> INFO : MINION : 264 [main] INFO org.evosuite.runtime.instrumentation.EvoClassLoader - Instrumenting class 'org.pitest.junit.adapter.ForeignClassLoaderCustomRunnerExecutor'.

8:22:12 PM PIT >> INFO : MINION : 1010 [main] INFO org.evosuite.runtime.instrumentation.EvoClassLoader - Seeing class for first time: org.pitest.reloc.xstream.io.HierarchicalStreamDriver

8:22:12 PM PIT >> INFO : MINION : 1010 [main] INFO org.evosuite.runtime.instrumentation.EvoClassLoader - Instrumenting class 'org.pitest.reloc.xstream.io.HierarchicalStreamDriver'.`

I am curious why Evosuite needs to instrument these classes from PITEST? 
What does Evosuite exactly do when instrumenting these classes? and is there any way to prevent this?

Actually I cannot successfully run PiTest on Evosuite, I always got the following exceptions:

`Please copy and paste the information and the complete stacktrace below when reporting an issue

VM : OpenJDK 64-Bit Server VM

Vendor : Oracle Corporation

Version : 25.91-b14

Uptime : 1666

Input ->

 1 : -javaagent:/tmp/14653022025

8:23:24 PM PIT >> INFO : MINION : 42031693225737969133763801195334263343.jar

BootClassPathSupported : true

```
    at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)

    at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:91)

    at org.pitest.cove
```

8:23:24 PM PIT >> INFO : MINION : rage.execute.CoverageDecorator.execute(CoverageDecorator.java:50)

```
    at org.pitest.testapi.execute.containers.UnContainer.execute(UnContainer.java:32)

    at org.pitest.testapi.execute.Pitest.executeTests(Pitest.java:59)

    at org.pitest.testapi.execute.Pitest.ru
```

8:23:24 PM PIT >> INFO : MINION : n(Pitest.java:50)

```
    at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:52)

    ... 1 more
```

Caused by: org.pitest.util.PitError:  : only whitespace content allowed before start tag and not j (position: START_DOCUMENT seen j... @1:1)

Please c

8:23:24 PM PIT >> INFO : MINION : opy and paste the information and the complete stacktrace below when reporting an issue

VM : OpenJDK 64-Bit Server VM

Vendor : Oracle Corporation

Version : 25.91-b14

Uptime : 1665

Input ->

 1 : -javaagent:/tmp/146530220254203169322573796913376380119533426

8:23:24 PM PIT >> INFO : MINION : 3343.jar

BootClassPathSupported : true

```
    at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)

    at org.pitest.junit.adapter.AdaptedJUnitTestUnit.executeInDifferentClassLoader(AdaptedJUnitTestUnit.java:153)

    at org.pitest.junit.adapter.A
```

8:23:24 PM PIT >> INFO : MINION : daptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:80)

```
    ... 6 more
```

Caused by: org.pitest.reloc.xstream.io.StreamException:  : only whitespace content allowed before start tag and not j (position: START_DOCUMENT seen j... @1:1)

```
    at org.pitest.reloc.xstr
```

8:23:24 PM PIT >> INFO : MINION : eam.io.xml.XppReader.pullNextEvent(XppReader.java:124)

```
    at org.pitest.reloc.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)

    at org.pitest.reloc.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141)

    at org.p
```

8:23:24 PM PIT >> INFO : MINION : itest.reloc.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118)

```
    at org.pitest.reloc.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103)

    at org.pitest.reloc.xstream.io.xml.XppReader.<init>(XppReader.java:63)

    at org.pit
```

8:23:24 PM PIT >> INFO : MINION : est.reloc.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54)

```
    at org.pitest.reloc.xstream.XStream.fromXML(XStream.java:1061)

    at org.pitest.reloc.xstream.XStream.fromXML(XStream.java:1052)

    at org.pitest.util.IsolationUtils.fromXml(Is
```

8:23:24 PM PIT >> INFO : MINION : olationUtils.java:124)

```
    at org.pitest.testapi.foreignclassloader.Events.applyEvents(Events.java:17)

    at org.pitest.junit.adapter.AdaptedJUnitTestUnit.convertStringsToResults(AdaptedJUnitTestUnit.java:160)

    at org.pitest.junit.adapter.AdaptedJUnitTestUnit.e
```

8:23:24 PM PIT >> INFO : MINION : xecuteInDifferentClassLoader(AdaptedJUnitTestUnit.java:151)

```
    ... 7 more
```

Caused by: org.pitest.reloc.xmlpull.v1.XmlPullParserException: only whitespace content allowed before start tag and not j (position: START_DOCUMENT seen j... @1:1)

```
    at org.pitest.relo
```

8:23:24 PM PIT >> INFO : MINION : c.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1519)

```
    at org.pitest.reloc.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)

    at org.pitest.reloc.xmlpull.mxp1.MXParser.next(MXParser.java:1093)

    at org.pitest.reloc.xstream.io.xml.XppReader.pullNextEvent(
```

8:23:24 PM PIT >> INFO : MINION : XppReader.java:109)

```
    ... 19 more
```

8:23:24 PM PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR

Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally!`

Thanks very much!

**Comment by arcuri82** [comment]
Hi,
  this issue should be already solved in the development snapshot, where we prevent the instrumentation of any "org.pitest." class

**Comment by arcuri82** [comment]
Hi,
  I made an alpha release (still few things to fix and more testing before a proper / official release) where this issue should had been fixed. Version is 1.0.4-alpha1, on Maven Central (http://search.maven.org/#search%7Cga%7C1%7Cevosuite). If you use an executable jar instead of Maven, download the one from http://repo1.maven.org/maven2/org/evosuite/evosuite-master/1.0.4-alpha1/

can you confirm whether the issue you reported has been solved or not?  

cheers

Andrea

**Comment by justinwm** [comment]
Thanks very much!
I will try that:-)

**Comment by gofraser** [comment]
It sounds like the original issue was fixed, so I am closing this issue. We've produced a simple PIT example and this seems to work: http://www.evosuite.org/documentation/measuring-code-coverage/
