### ISSUE TITLE
Error setting up EvoSuite on my Mac

### ISSUE THREAD

**Issue by khushiparashar** [EvoSuite/evosuite#361]
### Context
I am following the steps given on the EvoSuite site tutorials to install and set up EvoSUite for my Mac and generate the test suites for the file Tutorials_Stack. However, after compiling and cloning the Evosuite code from it's git repository,  when I try to run the .jar files I'm getting the following runtime error. 

[MASTER] 22:53:10.130 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1622913790127. Configuration id : null
java.lang.RuntimeException: Did not manage to automatically find tools.jar. Use -Dtools_jar_location=<path> property
        at org.evosuite.runtime.agent.ToolsJarLocator.getLoaderForToolsJar(ToolsJarLocator.java:105) ~[evosuite-1.0.6.jar:1.0.6]
        at org.evosuite.classpath.ClassPathHacker.initializeToolJar(ClassPathHacker.java:58) ~[evosuite-1.0.6.jar:1.0.6]
        at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:156) ~[evosuite-1.0.6.jar:1.0.6]
        at org.evosuite.EvoSuite.main(EvoSuite.java:302) ~[evosuite-1.0.6.jar:1.0.6]

 
 
How do I go about solving this error? Thank you!

**Comment by apanichella** [comment]
Which Java version are you using?
