### ISSUE TITLE
java.lang.IllegalArgumentException: null

### ISSUE THREAD

**Issue by shuqing1** [EvoSuite/evosuite#409]
Hello,
This is my fifth problem with EvoSuite, and I would like your guidance to solve them. Looking forward to your reply. Thank you!

mvn compile -DmemoryInMB=4000 -Dcores=4 -DtargetFolder=src/test/java evosuite:generate evosuite:export

All classes make this error:

std_err_CLIENT.log:
[MASTER] 17:26:04.668 [pool-2-thread-1] ERROR TestSuiteGenerator - Problem for xxxx. Full stack:
java.lang.IllegalArgumentException: null
	at org.evosuite.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
	at org.evosuite.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
	at org.evosuite.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
	at org.evosuite.setup.InheritanceTreeGenerator.analyzeClassStream(InheritanceTreeGenerator.java:238)
	at org.evosuite.setup.InheritanceTreeGenerator.createFromClassPath(InheritanceTreeGenerator.java:101)
	at org.evosuite.setup.DependencyAnalysis.initInheritanceTree(DependencyAnalysis.java:77)
	at org.evosuite.setup.DependencyAnalysis.analyzeClass(DependencyAnalysis.java:131)
	at org.evosuite.TestSuiteGenerator.initializeTargetClass(TestSuiteGenerator.java:110)
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:130)
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

std_err_MASTER.log"
[MASTER] 17:26:07.378 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 17:26:07.484 [main] ERROR TestGeneration - failed to write statistics data

std_out_CLIENT.log:
[MASTER] 17:26:04.737 [pool-2-thread-1] WARN  TimeController - Phase INITIALIZATION lasted too long, 4 seconds more than allowed.

std_out_MASTER.log:
* EvoSuite 1.0.6
* Configuration: default
* Going to generate test cases for class: xxxx
* Computation finished

**Comment by reply2techie** [comment]
Same problem. Did you find a solution?

**Comment by linxiaoyang** [comment]
Same problem. Did you find a solution?

**Comment by BensonMax** [comment]
Same problem. Did you find a solution?

**Comment by turanlioglu** [comment]
Hello, any solution found?
