### ISSUE TITLE
EvoSuite in Java 17

### ISSUE THREAD

**Issue by isadoracardosozup** [EvoSuite/evosuite#433]
I am trying to run EvoSuite in a Java 17 project, but it is not working since, currently, EvoSuite only supports Java up to 11. Has anyone had success running EvoSuite in Java 17? How much effort do we need to make EvoSuite work on Java 17? 

Below, you can see the EvoSuite response when trying to run in Java 17 project: 

```
* Error while initializing target class: br/com/zup/lms/alunos/Aluno has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
* Computation finished
[MASTER] 17:12:01.723 [logback-2] ERROR TestSuiteGenerator - Problem for br.com.zup.lms.alunos.Aluno. Full stack:
java.lang.ClassNotFoundException: br/com/zup/lms/alunos/Aluno has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:158)
        at org.evosuite.instrumentation.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:126)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:256)
        at org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:165)
        at org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:219)
        at org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:286)
        at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:192)
        at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:49)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsupportedClassVersionError: br/com/zup/lms/alunos/Aluno has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:878)
        at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:151)
        ... 17 common frames omitted
[MASTER] 17:12:01.845 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 17:12:01.947 [main] ERROR TestGeneration - failed to write statistics data
```

**Comment by jain-shreyansh** [comment]
any update on this?

**Comment by v1d3rm3** [comment]
Same here

**Comment by jfrchicanog** [comment]
Hi, we have a version of Evosuite running on Java 17. It is in a private repo but we would be happy to share it once we remove some details we cannot disclose.

**Comment by crhf** [comment]
@jfrchicanog hi, professor, have you got a chance to do this?

**Comment by JulienDiTria** [comment]
@jfrchicanog Hi i'd also be interested to go on java17, if you have a version that run on that ! let me know :)

**Comment by kenberland** [comment]
Yes, please share the Java 17 patch.

**Comment by MichelePolo** [comment]
I'm waiting with the others in this list of commente.

Thank you very much

**Comment by koppor** [comment]
Dear @jfrchicanog, it would be very nice if you could share the updates! Maybe using a pull request?

**Comment by wtwhite** [comment]
Hi @jfrchicanog, I'm another researcher who would be very much interested in your JDK17-capable fork of EvoSuite. Please let me know if I could help.

Thanks!

**Comment by may040** [comment]
Hello Professor @jfrchicanog ,

I am currently working with EvoSuite in my research. For this purpose, I really need EvoSuite to work with JDK 17.
Could you please publish the corresponding repository or provide instructions on how to build it myself?

Thank you very much in advance!

Best regards,

**Comment by vharatian** [comment]
Hi @jfrchicanog, I'm another researcher who is trying to use EvoSuit in our research projects. Is there any way we can get access to the version that supports JDK 17? 

Thanks!
