### ISSUE TITLE
Unable to find Snapshot version 1.0.7 and issues running EvoSuite 1.1.0 on Java 8 and 15

### ISSUE THREAD

**Issue by Juvemanu** [EvoSuite/evosuite#455]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

My initial goal is to generate tests with Evosuite 1.0.6 for specific methods. However, there seems to be a bug in this version as the 'target_method' argument and its derivatives are not working as expected, which is reported in #264. It has been suggested to try the snapshot 1.0.7 in #261 , but I have been unable to find this version. I've tried unsuccessfully to set it in the <version> of the pom file and also tried to get its Docker image from [Docker hub] [https://hub.docker.com/r/evosuite/evosuite]

Having no luck with the previous versions, I tried to run Evosuite version 1.1.0 in every way possible: through the plugin (which I could not find), jar, and Docker. I tried this with Java 8 (jdk1.8.0_202) and Java 15 (jdk-15.0.2). However, test generation fails without even trying to execute for specific methods with both versions of Java.

### Steps to Reproduce
For example, with Java 15, it tells me that there is no tools.jar, which makes sense since it was removed after Java 9:

1. Set the JAVA_HOME environment variable:
echo %JAVA_HOME%
C:\Program Files\Java\jdk-15.0.2

2. Execute EvoSuite:
java -jar evosuite-1.1.0.jar -class tutorial.LinkedList -projectCP target/classes

This results in a "Fatal crash on main EvoSuite process" with a "RuntimeException: Did not manage to automatically find tools.jar".

The steps are similar with Java 8, but the error output is different. See below for the detailed error output.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*

### Current Result
The EvoSuite command I executed is:
java -jar evosuite-1.1.0.jar -class tutorial.LinkedList -projectCP target/classes

With both Java 8 and Java 15, test generation fails, with different error outputs for each. I'll provide more details below.

1. Java 15: Fatal crash on the main EvoSuite process. RuntimeException: Did not manage to automatically find tools.jar. This is understandable since tools.jar was removed after Java 9.

`[MASTER] 19:43:17.872 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1685382197867. Configuration id : null
java.lang.RuntimeException: Did not manage to automatically find tools.jar. Use -Dtools_jar_location=<path> property
        at org.evosuite.runtime.agent.ToolsJarLocator.getLoaderForToolsJar(ToolsJarLocator.java:116)
        at org.evosuite.classpath.ClassPathHacker.initializeToolJar(ClassPathHacker.java:69)
        at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:191)
        at org.evosuite.EvoSuite.main(EvoSuite.java:115)
`

3. Java 8: The test generation starts and finishes without apparent problems. However, during the "Compiling and checking tests" phase, an IllegalStateException error occurs related to the attachment using ByteBuddyAgent$AttachmentProvider$Compound.
 
`[MASTER] 20:50:45.904 [logback-2] ERROR AgentLoader - Exception class java.lang.IllegalStateException: Error during attachment using: org.evosuite.shaded.net.bytebuddy.agent.ByteBuddyA
gent$AttachmentProvider$Compound@33bbbd34 , cause class java.lang.reflect.InvocationTargetException null
java.lang.IllegalStateException: Error during attachment using: org.evosuite.shaded.net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@33bbbd34
        at org.evosuite.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613)
        at org.evosuite.shaded.net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:273)
        at org.evosuite.shaded.net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:238)
`

### Additional info
I have used the classes from the official tutorial part 2.

 I can provide more detailed error outputs if required.

**Comment by reply2techie** [comment]
Let me know if you find an answer. I have a similar issue and Evosuite seems to have stopped rolling out new versions to support jdk 17 and similar upgrades.

**Comment by may040** [comment]
I also have the third problem. It is also showing that the agent is not loading properly. However, when debugging, I can see the correct JAR, which is evosuite-master-1.2.1-SNAPSHOT-shaded.jar. Can this please be fixed?

![Image](https://github.com/user-attachments/assets/7e1d54ee-060e-4c52-9162-a89d8ed6543b)

![Image](https://github.com/user-attachments/assets/ff90c2b9-411c-4876-827d-9a30604b672d)

The agent is here why ???

![Image](https://github.com/user-attachments/assets/38ddd25d-532c-410d-b9ed-58fbb0bfe073)

**Comment by may040** [comment]
![Image](https://github.com/user-attachments/assets/0632cc3f-9778-44c1-b1e1-12bdb3eb23b3)
in the pom.xml of evosuite-master ???
