### ISSUE TITLE
 class com.sun.tools.attach.AttachNotSupportedException no providers installed

### ISSUE THREAD

**Issue by Pablocgdev** [EvoSuite/evosuite#47]
This error makes no sense, in my evosuite.properties I'm loading tools.jar and I'm also loading the jar through command line ( -Dtools_jar_location="tools.jar" )
```
[MASTER] 11:51:10.708 [logback-2] ERROR JUnitAnalyzer - 1 test cases failed
[MASTER] 11:51:10.710 [logback-1] WARN  JUnitAnalyzer - Found unstable test named initializationError -> class java.lang.RuntimeEx
ception: java.lang.reflect.InvocationTargetException
[MASTER] 11:51:12.429 [logback-2] ERROR AgentLoader - Exception class java.lang.reflect.InvocationTargetException: null , cause cl
ass com.sun.tools.attach.AttachNotSupportedException no providers installed
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_91]
        at org.evosuite.runtime.agent.AgentLoader.attachAgent(AgentLoader.java:118) ~[evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.runtime.agent.AgentLoader.loadAgent(AgentLoader.java:88) ~[evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.runtime.agent.InstrumentingAgent.initialize(InstrumentingAgent.java:101) [evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.runtime.EvoRunner.getClass(EvoRunner.java:96) [evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.runtime.EvoRunner.<init>(EvoRunner.java:72) [evosuite-1.0.3.jar:1.0.3]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_91]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [na:1.8.0_91]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [na:1.8.0_91]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) [na:1.8.0_91]
        at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104) [evosuite-1.0.3.jar:1.0.3]
        at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86) [evosuite-1.0.3.jar:1.0.3]
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [evosuite-1.0.3.jar:1.0.3]
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26) [evos
uite-1.0.3.jar:1.0.3]
        at org.junit.runner.Computer.getRunner(Computer.java:40) [evosuite-1.0.3.jar:1.0.3]
        at org.junit.runner.Computer$1.runnerForClass(Computer.java:31) [evosuite-1.0.3.jar:1.0.3]
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [evosuite-1.0.3.jar:1.0.3]
        at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101) [evosuite-1.0.3.jar:1.0.3]
        at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87) [evosuite-1.0.3.jar:1.0.3]
        at org.junit.runners.Suite.<init>(Suite.java:81) [evosuite-1.0.3.jar:1.0.3]
        at org.junit.runner.Computer.getSuite(Computer.java:28) [evosuite-1.0.3.jar:1.0.3]
        at org.junit.runner.Request.classes(Request.java:75) [evosuite-1.0.3.jar:1.0.3]
        at org.junit.runner.JUnitCore.run(JUnitCore.java:105) [evosuite-1.0.3.jar:1.0.3]
        at org.junit.runner.JUnitCore.run(JUnitCore.java:94) [evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.junit.JUnitAnalyzer.runJUnitOnCurrentProcess(JUnitAnalyzer.java:293) [evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.junit.JUnitAnalyzer.runTests(JUnitAnalyzer.java:267) [evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.junit.JUnitAnalyzer.handleTestsThatAreUnstable(JUnitAnalyzer.java:176) [evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.TestSuiteGenerator.compileAndCheckTests(TestSuiteGenerator.java:388) [evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.TestSuiteGenerator.postProcessTests(TestSuiteGenerator.java:332) [evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:148) [evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) [evosuite-1.0.3.jar:1.0.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_91]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]
Caused by: com.sun.tools.attach.AttachNotSupportedException: no providers installed
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:203) ~[tools.jar:na]
        ... 39 common frames omitted
```

This exception appears many times while evosuite is generating my test files. I've tried everything I've found about tools.jar: adding to the CP, inyecting the .jar manually, creating evosuite.properties file, moving the .jar...

**Comment by arcuri82** [comment]
Hi,
  there is a known issue with JavaAgent if you have PowerMock or JMockit on the classpath, but should be fixed on the develop branch (not 1.0.3). You can try to use the jar at 

``http://search.maven.org/remotecontent?filepath=org/evosuite/evosuite-master/1.0.4-alpha2/evosuite-master-1.0.4-alpha2.jar``

and see if you still get the same issue

**Comment by Pablocgdev** [comment]
j```
ava.lang.RuntimeException: Missing com.sun.tools.attach.VirtualMachine in tools.jar
        at org.evosuite.runtime.agent.ToolsJarLocator.validateAndGetLoader(ToolsJarLocator.java:132) ~[evosuite4.jar:1.0.4-alpha2]

        at org.evosuite.runtime.agent.ToolsJarLocator.considerPathInProperties(ToolsJarLocator.java:113) ~[evosuite4.jar:1.0.4-alp
ha2]
        at org.evosuite.runtime.agent.ToolsJarLocator.getLoaderForToolsJar(ToolsJarLocator.java:78) ~[evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.classpath.ClassPathHacker.initializeToolJar(ClassPathHacker.java:58) ~[evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.ClientProcess.initializeToolJar(ClientProcess.java:109) ~[evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.ClientProcess.run(ClientProcess.java:74) ~[evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.ClientProcess.main(ClientProcess.java:203) ~[evosuite4.jar:1.0.4-alpha2]

```

It happens in every class.

**Comment by arcuri82** [comment]
hmmmm... weird

when you wrote:

``In my evosuite.properties I'm loading tools.jar and I'm also loading the jar through command line ( -Dtools_jar_location="tools.jar" )``

why did u have to specify the tools.jar location? Did EvoSuite fail to find it automatically? 
When you write:

``-Dtools_jar_location="tools.jar"``

I assume you do not use the string "tools.jar", but the actual absolute path to its location?

which version of Windows and JDK are you using?

**Comment by Pablocgdev** [comment]
Yes, when I tried  `-Dtools_jar_location="tools.jar"` the .jar was on the root so that was the correct path.

If I try to run the plugin without tools.jar manual injection:

```
[MASTER] 09:15:56.292 [logback-2] ERROR AgentLoader - Exception class java.lang.RuntimeException: AttachProvider.providers() faile
d to return any provider. Tool classloader: java.net.FactoryURLClassLoader@794104ca
java.lang.RuntimeException: AttachProvider.providers() failed to return any provider. Tool classloader: java.net.FactoryURLClassLo
ader@794104ca
        at org.evosuite.runtime.agent.AgentLoader.attachAgent(AgentLoader.java:122) ~[evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.runtime.agent.AgentLoader.loadAgent(AgentLoader.java:89) ~[evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.runtime.agent.InstrumentingAgent.initialize(InstrumentingAgent.java:101) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.runtime.EvoRunner.getClass(EvoRunner.java:102) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.runtime.EvoRunner.<init>(EvoRunner.java:77) [evosuite4.jar:1.0.4-alpha2]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_91]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [na:1.8.0_91]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [na:1.8.0_91]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) [na:1.8.0_91]
        at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26) [evos
uite4.jar:1.0.4-alpha2]
        at org.junit.runner.Computer.getRunner(Computer.java:40) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runner.Computer$1.runnerForClass(Computer.java:31) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runners.Suite.<init>(Suite.java:81) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runner.Computer.getSuite(Computer.java:28) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runner.Request.classes(Request.java:75) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runner.JUnitCore.run(JUnitCore.java:105) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runner.JUnitCore.run(JUnitCore.java:94) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.junit.JUnitAnalyzer.runJUnitOnCurrentProcess(JUnitAnalyzer.java:298) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.junit.JUnitAnalyzer.runTests(JUnitAnalyzer.java:267) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.junit.JUnitAnalyzer.handleTestsThatAreUnstable(JUnitAnalyzer.java:176) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.TestSuiteGenerator.compileAndCheckTests(TestSuiteGenerator.java:552) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.TestSuiteGenerator.postProcessTests(TestSuiteGenerator.java:495) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:195) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) [evosuite4.jar:1.0.4-alpha2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_91]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]
```

**Comment by Pablocgdev** [comment]
`[MASTER] 09:52:48.664 [logback-2] ERROR AgentLoader - Exception class java.lang.RuntimeException: AttachProvider.providers() faile
d to return any provider. Tool classloader: java.net.FactoryURLClassLoader@78b34da3
java.lang.RuntimeException: AttachProvider.providers() failed to return any provider. Tool classloader: java.net.FactoryURLClassLo
ader@78b34da3
        at org.evosuite.runtime.agent.AgentLoader.attachAgent(AgentLoader.java:122) ~[evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.runtime.agent.AgentLoader.loadAgent(AgentLoader.java:89) ~[evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.runtime.agent.InstrumentingAgent.initialize(InstrumentingAgent.java:101) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.runtime.EvoRunner.getClass(EvoRunner.java:102) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.runtime.EvoRunner.<init>(EvoRunner.java:77) [evosuite4.jar:1.0.4-alpha2]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_91]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [na:1.8.0_91]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [na:1.8.0_91]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) [na:1.8.0_91]
        at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26) [evos
uite4.jar:1.0.4-alpha2]
        at org.junit.runner.Computer.getRunner(Computer.java:40) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runner.Computer$1.runnerForClass(Computer.java:31) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runners.Suite.<init>(Suite.java:81) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runner.Computer.getSuite(Computer.java:28) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runner.Request.classes(Request.java:75) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runner.JUnitCore.run(JUnitCore.java:105) [evosuite4.jar:1.0.4-alpha2]
        at org.junit.runner.JUnitCore.run(JUnitCore.java:94) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.junit.JUnitAnalyzer.runJUnitOnCurrentProcess(JUnitAnalyzer.java:298) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.junit.JUnitAnalyzer.runTests(JUnitAnalyzer.java:267) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.junit.JUnitAnalyzer.handleTestsThatAreUnstable(JUnitAnalyzer.java:176) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.TestSuiteGenerator.compileAndCheckTests(TestSuiteGenerator.java:552) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.TestSuiteGenerator.postProcessTests(TestSuiteGenerator.java:495) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:195) [evosuite4.jar:1.0.4-alpha2]
        at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) [evosuite4.jar:1.0.4-alpha2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_91]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]
`

`[MASTER] 09:55:29.721 [logback-1] WARN  MethodDescriptor - Could not load the SUT
`

Error persists on 1.4 alpha. Same error if I inject tools.jar manually or I don't inject it at all. Im running jdk1.8.0_91.

**Comment by arcuri82** [comment]
Hi,
  it would be interesting to see if it is a problem due to project settings or OS settings. If you run ES on a new simple project with eg just one simple class, do you see the same problem? 

In the project you used ES on, was there any third-library including classes from ``com.sun.tools`` ?

**Comment by merric** [comment]
I'm seeing this when I do a mvn install. I'm using 1.0.1 with the following possibly related dependancies: 

        <maven-antrun-plugin.version>1.7</maven-antrun-plugin.version>
        <maven-compiler-plugin.version>3.1</maven-compiler-plugin.version>
        <maven-eclipse-plugin.version>2.9</maven-eclipse-plugin.version>
        <maven-install-plugin.version>2.5.1</maven-install-plugin.version>
        <maven-jar-plugin.version>2.4</maven-jar-plugin.version>
        <maven-replacer-plugin.version>1.4.1</maven-replacer-plugin.version>
        <maven-resources-plugin.version>2.6</maven-resources-plugin.version>
        <maven-surefire-plugin.version>2.16</maven-surefire-plugin.version>
        <maven-version-plugin.version>1.0</maven-version-plugin.version>
        <maven-war-plugin.version>2.4</maven-war-plugin.version>
        <maven-ear-plugin.version>2.10.1</maven-ear-plugin.version>
        <maven-assembly-plugin.version>2.4</maven-assembly-plugin.version>

 <hamcrest.version>1.3</hamcrest.version>
        <junit.version>4.12</junit.version>
        <javaee-api.version>7.0</javaee-api.version>
        <mockito.version>1.10.19</mockito.version>
        <powermock.version>1.6.4</powermock.version>

        <jmockit.version>1.8</jmockit.version>
        <jmockit.agent>
            ${settings.localRepository}/org/jmockit/jmockit/${jmockit.version}/jmockit-${jmockit.version}.jar
        </jmockit.agent>
        <jmockit.argLine>"-javaagent:${jmockit.agent}"</jmockit.argLine>

**Comment by merric** [comment]
Is there a plan to put the development version on your m2 repo?

**Comment by gofraser** [comment]
We'll upload a new release 1.0.4 this weekend.

**Comment by merric** [comment]
Hey Gordon, 

I'm not seeing the new release up on http://www.evosuite.org/m2/ was that able to happen this weekend?

**Comment by merric** [comment]
Any thoughts on the "AttachNotSupportedException no providers installed" bug?

**Comment by gofraser** [comment]
Sorry I am travelling until the end of the week so the new release will probably be delayed until I'm back (you could check out the source and build it yourself if it's urgent...)

**Comment by mr-yusupov** [comment]
Is there any news on this @gofraser ? Bug still exists

**Comment by sinaa** [comment]
@mr-yusupov Evosuite 1.0.4 was released around 2 months ago ( https://github.com/EvoSuite/evosuite/releases ).

Are you still having the problem with the latest version of evosuite?

If so, please submit a new issue with all necessary details to replicate it.

**Comment by JavaJimFl** [comment]
I see this error with v1.0.5 when building/testing with Maven.  

I can generate unit tests on a JMockit-enabled project using either the Maven plugin or the command line, but when I try to run them using Maven they fail with the '_java.lang.reflect.InvocationTargetException: null , cause class com.sun.tools.attach.AttachNotSupportedException_' mentioned above if I use 'evosuite-standalone-runtime' as a Maven dependency.  If I swap out that dependeny with 'evosuite-master', the tests work as expected.

**Comment by lamrin13** [comment]
Hey, I am using version 1.2.0 and using jar files to generate tests. I am getting similar errors,

[MASTER] 12:55:49.988 [logback-2] ERROR AgentLoader - Exception class java.lang.IllegalStateException: Error during attachment using: org.evosuite.shaded.net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@16f4abe4 , cause class java.lang.reflect.InvocationTargetException null
java.lang.IllegalStateException: Error during attachment using: org.evosuite.shaded.net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@16f4abe4
        at org.evosuite.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:636)
        at org.evosuite.shaded.net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:296)
        at org.evosuite.shaded.net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:261)
        at org.evosuite.shaded.net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:243)
        at org.evosuite.runtime.agent.AgentLoader.attachAgent(AgentLoader.java:129)
        at org.evosuite.runtime.agent.AgentLoader.loadAgent(AgentLoader.java:90)
        at org.evosuite.runtime.agent.InstrumentingAgent.initialize(InstrumentingAgent.java:102)
        at org.evosuite.runtime.EvoRunner.getClass(EvoRunner.java:101)
        at org.evosuite.runtime.EvoRunner.<init>(EvoRunner.java:76)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

I am using this command to run the code,
java -jar evosuite-1.2.0.jar -class com.hascode.tutorial.MyApp -projectCP target/classes
