### ISSUE TITLE
Class not found exception

### ISSUE THREAD

**Issue by gauravr2** [EvoSuite/evosuite#471]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*
I am trying to run evosuite on QuixBugs buggy and patched sets. I was using Java 20, it was causing certain dependency issue. Then I tried using Java 8 and 11, getting another error, stack trace is mentioned below.

I have run randoop on the same and faced no issues and classpath is correct, help needed to figure out the issue.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

Run the below command in the source directory of QuixBugs.
java -jar evosuite-1.2.0.jar -target java_programs -class BITCOUNT

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*
java -jar evosuite-1.2.0.jar -target java_programs -class BITCOUNT

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

java -jar evosuite-1.2.0.jar -target java_programs -class BITCOUNT
* EvoSuite 1.2.0
* Going to generate test cases for class: BITCOUNT
* Starting Client-0
* Connecting to master process on port 13246
* Analyzing classpath: 
  - java_programs
* Error while initializing target class: java_programs/BITCOUNT (wrong name: BITCOUNT)
[MASTER] 22:46:40.757 [logback-2] ERROR TestSuiteGenerator - Problem for BITCOUNT. Full stack:
java.lang.ClassNotFoundException: java_programs/BITCOUNT (wrong name: BITCOUNT)
        at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:158)
        at org.evosuite.instrumentation.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:126)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:256)
        at org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:165)
        at org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:219)
        at org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:286)
        at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:192)
        at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:49)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: java_programs/BITCOUNT (wrong name: BITCOUNT)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
        at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:151)
        ... 17 common frames omitted
* Computation finished
[MASTER] 22:46:40.879 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 22:46:40.986 [main] ERROR TestGeneration - failed to write statistics data

**Comment by gauravr2** [comment]
Resolved
