### ISSUE TITLE
Error while initializing target class: java.lang.NullPointerException ASTER] 14:15:48.323 [logback-2] ERROR TestSuiteGenerator

### ISSUE THREAD

**Issue by miggymigz** [EvoSuite/evosuite#55]
```
* Error while initializing target class: java.lang.NullPointerException
[MASTER] 14:15:48.323 [logback-2] ERROR TestSuiteGenerator - Problem for xx.xxx.SampleClass. Full stack:
java.lang.NullPointerException: null
        at org.evosuite.setup.PutStaticMethodCollector.collectMethods(PutStaticMethodCollector.java:144) ~[evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.setup.TestClusterGenerator.initializeTargetMethods(TestClusterGenerator.java:641) ~[evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.setup.TestClusterGenerator.generateCluster(TestClusterGenerator.java:135) ~[evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.setup.DependencyAnalysis.analyze(DependencyAnalysis.java:117) ~[evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.setup.DependencyAnalysis.analyzeClass(DependencyAnalysis.java:131) ~[evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:110) ~[evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) [evosuite-1.0.3.jar:1.0.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
* Computation finished
[MASTER] 14:15:50.773 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 14:15:50.882 [main] ERROR TestGeneration - failed to write statistics data
```

any help with this ?

**Comment by gofraser** [comment]
Is there any chance I could get access to this xx.xxx.SampleClass, or a minimised/anonymised version to reproduce the problem? Does this class have some inner classes by any chance?

**Comment by gofraser** [comment]
Without further information, I cannot reproduce this. We've tested the current release (1.0.5) on >20K classes without seeing this problem, so I'll assume this has been fixed. If the problem persists, please re-open this issue.

**Comment by rshoemake** [comment]
I'm actually having the same exact issue, but I work at a bank.  So, I wont be able to provide any class details.

**Comment by rshoemake** [comment]
is it possible to look at the stack trace provided above, and work backwards tryign to figure out how that can be null?

**Comment by rshoemake** [comment]
I can tell you that it happens in the 2nd level subclass.  So I have  
BaseJsonEntity ->  BaseOperationIO ->  OperationRequest 
   ^tests generated          ^tests generated         ^no tests generated due to stack trace above

Looking at the EvoSuite code seems to indicate it's looking at static methods.  I have the following :             
In the BaseJsonEntity
private static String standardcustomFieldFormat = "customfield_%s";

        public static String key(String identifier) {
                return BaseJsonEntity.key(identifier, null);
        }

        public static String key(String identifier, String format) {
                BaseJsonEntity self = new BaseJsonEntity(format);
                return String.format(self.customFieldFormat, identifier);
        }

In the BaseOperationIO
        private static final long serialVersionUID = 1L;

That's it for static methods and members/

**Comment by gofraser** [comment]
What arguments exactly do you use when invoking EvoSuite?

I'm not sure I fully understand your example -- you can test BaseJsonEntity and BaseOperationIO, but get the error when invoking EvoSuite on OperationRequest (which is the superclass of the other classes)?

**Comment by gofraser** [comment]
Could you maybe run EvoSuite using -Dlog.level=debug and show me the resulting output?

**Comment by Barry1915** [comment]
![image](https://user-images.githubusercontent.com/76513632/163955992-9b4ee89a-2e2a-49ae-aaa3-36a0e7febc98.png)

**Comment by Barry1915** [comment]
![image](https://user-images.githubusercontent.com/76513632/163958757-de77f75b-598c-46d4-9be2-8b71289834d1.png)

**Comment by vivekshubhu** [comment]
Has anyone solved this? I am getting this error in all of my classes

**Comment by vivekshubhu** [comment]
`
* Error while initializing target class: java.lang.NullPointerException
[MASTER] 22:33:00.782 [logback-2] ERROR TestSuiteGenerator - Problem for com.prounlimited.billing.service.approval.BillingApprovalService. Full stack:
java.lang.NullPointerException: null
        at org.evosuite.setup.PutStaticMethodCollector.collectMethods(PutStaticMethodCollector.java:144) ~[evosuite.jar:1.0.6]
        at org.evosuite.setup.TestClusterGenerator.initializeTargetMethods(TestClusterGenerator.java:697) ~[evosuite.jar:1.0.6]
        at org.evosuite.setup.TestClusterGenerator.generateCluster(TestClusterGenerator.java:134) ~[evosuite.jar:1.0.6]
        at org.evosuite.setup.DependencyAnalysis.analyze(DependencyAnalysis.java:118) ~[evosuite.jar:1.0.6]
        at org.evosuite.setup.DependencyAnalysis.analyzeClass(DependencyAnalysis.java:132) ~[evosuite.jar:1.0.6]
        at org.evosuite.TestSuiteGenerator.initializeTargetClass(TestSuiteGenerator.java:110) ~[evosuite.jar:1.0.6]
        at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:130) ~[evosuite.jar:1.0.6]
        at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) [evosuite.jar:1.0.6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_352]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [na:1.8.0_352]
* Computation finished
[MASTER] 22:33:03.484 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 22:33:03.594 [main] ERROR TestGeneration - failed to write statistics data

`
