### ISSUE TITLE
not able to generate EvoSuite test suite

### ISSUE THREAD

**Issue by ajmersaini** [EvoSuite/evosuite#77]
I am following instructions of 
http://www.evosuite.org/documentation/tutorial-part-1/

Everything goes fine but when i used following command .

java org.junit.runner.JUnitCore tutorial.Stack_ESTest

it shows run time error as below 

      
C:\Tutorial_Stack> java org.junit.runner.JUnitCore tutorial.Stack_ESTest
JUnit version 4.12
Exception in thread "main" java.lang.NoClassDefFoundError: tutorial/Stack_ESTest_scaffolding
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.junit.internal.Classes.getClass(Classes.java:16)
        at org.junit.runner.JUnitCommandLineParseResult.parseParameters(JUnitCommandLineParseResult.java:100)
        at org.junit.runner.JUnitCommandLineParseResult.parseArgs(JUnitCommandLineParseResult.java:50)
        at org.junit.runner.JUnitCommandLineParseResult.parse(JUnitCommandLineParseResult.java:44)
        at org.junit.runner.JUnitCore.runMain(JUnitCore.java:72)
        at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
Caused by: java.lang.ClassNotFoundException: tutorial.Stack_ESTest_scaffolding
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 20 more

please help

**Comment by sinaa** [comment]
The error is due to the class not being on the classpath.

The `export CLASSPATH` command uses unix classpath parameters (`:` seperated). Given that you're on Windows, you need to use the Windows path separator (`;`) instead.

Please also note that the Github issues is for actual bugs/issues with Evosuite, and is not a product support forum.
