### ISSUE TITLE
Many errors occurred when I used evosuite-1.0.3.jar in commandline 

### ISSUE THREAD

**Issue by LDily** [EvoSuite/evosuite#82]
commandline: "java -jar evosuite.jar -class Hytera.dao.BaseDao -DCP_file_path=jar1.txt -Dtest_naming_strategy=coverage", I can't solve these errors.
thank you

[MASTER] 11:08:20.129 [logback-2] ERROR TestClusterGenerator - Problem for Hytera.timedTask.SysJobService. Failed to add dependencies for class org.apache.log4j.TTCCLayout: java.lang.VerifyError: (class: org/apache/log4j/helpers/DateLayout, method: setDateFormat signature: (Ljava/lang/String;Ljava/util/TimeZone;)V) Bad type in putfield/putstatic
[java.lang.Class.getDeclaredMethods0(Native Method), java.lang.Class.privateGetDeclaredMethods(Class.java:2701), java.lang.Class.getDeclaredMethods(Class.java:1975), org.evosuite.setup.TestClusterUtils.getMethods(TestClusterUtils.java:304), org.evosuite.setup.TestClusterUtils.getMethods(TestClusterUtils.java:293), org.evosuite.setup.TestClusterGenerator.addDependencyClass(TestClusterGenerator.java:893), org.evosuite.setup.TestClusterGenerator.resolveDependencies(TestClusterGenerator.java:332), org.evosuite.setup.TestClusterGenerator.generateCluster(TestClusterGenerator.java:138), org.evosuite.setup.DependencyAnalysis.analyze(DependencyAnalysis.java:117), org.evosuite.setup.DependencyAnalysis.analyzeClass(DependencyAnalysis.java:131), org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:110), org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)]
[MASTER] 11:08:40.415 [logback-2] ERROR ClientNodeImpl - Error when generating tests for: Hytera.timedTask.SysJobService with seed 1488424078248. Configuration id : null
java.lang.TypeNotPresentException: Type joptsimple.OptionSet not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117) ~[na:1.8.0_65]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[na:1.8.0_65]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:1.8.0_65]
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[na:1.8.0_65]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[na:1.8.0_65]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:1.8.0_65]
	at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:90) ~[na:1.8.0_65]
	at java.lang.Class.getGenericSuperclass(Class.java:777) ~[na:1.8.0_65]
	at com.googlecode.gentyref.GenericTypeReflector.getExactDirectSuperTypes(GenericTypeReflector.java:284) ~[evosuite-1.0.3.jar:1.0.3]
	at com.googlecode.gentyref.GenericTypeReflector.getExactSuperType(GenericTypeReflector.java:138) ~[evosuite-1.0.3.jar:1.0.3]

**Comment by gofraser** [comment]
Thanks. Can you please confirm whether this also happens with 1.0.4 (https://github.com/EvoSuite/evosuite/releases/tag/1.0.4)? If so we'll need some more information to debug this. Is the Java class that causes the error available somewhere, or can you produce a minimal example that exhibits this problem?

**Comment by LDily** [comment]
OK, I'll try. Thank you

**Comment by LDily** [comment]
Thanks. The above mistakes are gone in edition 1.0.4, but there are still other errors.
I have also encountered this kind of error in other classes, for instance, Class not found: org.springframework.scheduling.commonj.TimerManagerTaskScheduler$ReschedulingTimerListener
java.lang.ClassNotFoundException: commonj/timers/TimerListener


[MASTER] 09:45:39.478 [logback-2] ERROR ConcreteClassAnalyzer - Problem for Hytera.timedTask.SysJobService. Class not found: org.springframework.context.support.GenericGroovyApplicationContext
java.lang.ClassNotFoundException: groovy/lang/GroovyObject
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:201) ~[evosuite-1.0.4.jar:1.0.4]
	at org.evosuite.instrumentation.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:168) ~[evosuite-1.0.4.jar:1.0.4]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_65]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_65]
	at org.evosuite.setup.ConcreteClassAnalyzer.getConcreteClassesImpl(ConcreteClassAnalyzer.java:126) [evosuite-1.0.4.jar:1.0.4]
	at org.evosuite.setup.ConcreteClassAnalyzer.getConcreteClasses(ConcreteClassAnalyzer.java:61) [evosuite-1.0.4.jar:1.0.4]
	at org.evosuite.setup.TestClusterGenerator.addDependency(TestClusterGenerator.java:843) [evosuite-1.0.4.jar:1.0.4]
	at org.evosuite.setup.TestClusterGenerator.addDependencies(TestClusterGenerator.java:754) [evosuite-1.0.4.jar:1.0.4]
	at org.evosuite.setup.TestClusterGenerator.initializeTargetMethods(TestClusterGenerator.java:537) [evosuite-1.0.4.jar:1.0.4]
	at org.evosuite.setup.TestClusterGenerator.generateCluster(TestClusterGenerator.java:134) [evosuite-1.0.4.jar:1.0.4]
	at org.evosuite.setup.DependencyAnalysis.analyze(DependencyAnalysis.java:117) [evosuite-1.0.4.jar:1.0.4]
	at org.evosuite.setup.DependencyAnalysis.analyzeClass(DependencyAnalysis.java:131) [evosuite-1.0.4.jar:1.0.4]
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:135) [evosuite-1.0.4.jar:1.0.4]
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) [evosuite-1.0.4.jar:1.0.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: java.lang.NoClassDefFoundError: groovy/lang/GroovyObject
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[na:1.8.0_65]
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:194) ~[evosuite-1.0.4.jar:1.0.4]
	... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: Class 'groovy/lang/GroovyObject.class' should be in target project, but could not be found!
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:201) ~[evosuite-1.0.4.jar:1.0.4]
	at org.evosuite.instrumentation.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:168) ~[evosuite-1.0.4.jar:1.0.4]
	... 22 common frames omitted
Caused by: java.lang.ClassNotFoundException: Class 'groovy/lang/GroovyObject.class' should be in target project, but could not be found!
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:188) ~[evosuite-1.0.4.jar:1.0.4]
	... 23 common frames omitted
[MASTER] 09:45:39.478 [logback-2] ERROR ConcreteClassAnalyzer - Removing class from inheritance tree

**Comment by gofraser** [comment]
These errors mean that there are some dependencies missing on your classpath, in this case the groovy library. (There might be other problems when generating tests for groovy, see #75).

I'll close this issue since the original problem is already fixed.

**Comment by LDily** [comment]
But I didn't use the groovy library in my class, why did it make this error?
Thank you.

**Comment by gofraser** [comment]
You might have a direct or indirect dependency on a Groovy library. But I assume EvoSuite runs anyway, and just complains about this, right?

**Comment by LDily** [comment]
Thank you very much. It worked.
But It didn't generate any test case.

**Comment by IndyPaula** [comment]
Hi LDily, 

This class that you selected has a ".class"? I had one problem like this when I was running the test with the Evosuite. I verified all my libs, dependencies and the organization of project. As well, I checked all .class.

**Comment by IndyPaula** [comment]
I used the version Evosuite 1.0.3 and i got to generated some suites.

**Comment by LDily** [comment]
Hi IndyPaula,
The problem was resolved in edition 1.0.4, you may try the new edition.
