### ISSUE TITLE
Are there Scalability Issues in mutation criteria

### ISSUE THREAD

**Issue by claudejin** [EvoSuite/evosuite#88]
I run EvoSuite with strong mutation criterion on a large class (Math-59 from Defects4J).
Without any special parameters, I can get a resulting test suite successfully.

However, when I change maximum number of mutants per class(-Dmax_mutants_per_class), I see the series of errors. Interesting is that errors were different by values that I gave. I adds logs of the two different cases.

I think that Case 1 happens from an external library which is ASM, and the class writer itself cannot handle the large instrumentations. However, I don't have any guess on Case 2.

Could you tell me any suspicious reasons for those cases?

I'm using EvoSuite 1.0.4, Java 1.8, 

Case 1: max_mutants_per_class=10000
```
* EvoSuite 1.0.4
* Going to generate test cases for class: org.apache.commons.math.util.FastMath
* Starting client
* Connecting to master process on port 11729
* Analyzing classpath: 
* Error while initializing target class: Class file too large!
[MASTER] 03:33:45.053 [logback-2] ERROR TestSuiteGenerator - Problem for org.apache.commons.math.util.FastMath. Full stack:
java.lang.ClassNotFoundException: Class file too large!
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:201) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.instrumentation.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:168) ~[evosuite-current.jar:1.0.4]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_121]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:306) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:212) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55) ~[evosuite-current.jar:1.0.4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.lang.RuntimeException: Class file too large!
	at org.evosuite.shaded.org.objectweb.asm.ClassWriter.toByteArray(Unknown Source) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.instrumentation.BytecodeInstrumentation.transformBytes(BytecodeInstrumentation.java:285) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.instrumentation.InstrumentingClassLoader.getTransformedBytes(InstrumentingClassLoader.java:175) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:192) ~[evosuite-current.jar:1.0.4]
	... 17 common frames omitted
* Computation finished
[MASTER] 03:33:45.686 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 03:33:45.787 [main] ERROR TestGeneration - failed to write statistics data
```

Case 2: max_mutants_per_class=5000
```
* EvoSuite 1.0.4
* Going to generate test cases for class: org.apache.commons.math.util.FastMath
* Starting client
* Connecting to master process on port 14410
* Analyzing classpath: 
  - /tmp/run_evosuite.pl_8964_1489575561/target/classes
* Finished analyzing classpath
* Generating tests for class org.apache.commons.math.util.FastMath
* Test criterion:
  - Mutation testing (strong)
* Setting up search algorithm for whole suite generation
* Total number of test goals: 2812
* Using seed 1489575571593
* Starting evolution
* Search finished after 231s and 0 generations, 47134 statements, best individual has fitness: 6221.395046140188
[MASTER] 04:03:46.574 [logback-2] ERROR ClientNodeImpl - Cannot inform master of change of state
java.rmi.ServerException: RemoteException occurred in server thread; nested exception is: 
	java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is: 
	java.lang.ClassNotFoundException: expect to get instruction without BasicBlock already set
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:377) ~[na:1.8.0_121]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) ~[na:1.8.0_121]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276) ~[na:1.8.0_121]
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253) ~[na:1.8.0_121]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162) ~[na:1.8.0_121]
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227) ~[na:1.8.0_121]
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179) ~[na:1.8.0_121]
	at com.sun.proxy.$Proxy7.evosuite_collectStatistics(Unknown Source) ~[na:na]
	at org.evosuite.rmi.service.ClientNodeImpl.updateStatistics(ClientNodeImpl.java:237) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.statistics.StatisticsSender.sendIndividualToMaster(StatisticsSender.java:68) [evosuite-current.jar:1.0.4]
	at org.evosuite.statistics.StatisticsSender.executedAndThenSendIndividualToMaster(StatisticsSender.java:98) [evosuite-current.jar:1.0.4]
	at org.evosuite.TestSuiteGenerator.generateTests(TestSuiteGenerator.java:647) [evosuite-current.jar:1.0.4]
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:208) [evosuite-current.jar:1.0.4]
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) [evosuite-current.jar:1.0.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is: 
	java.lang.ClassNotFoundException: expect to get instruction without BasicBlock already set
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:337) ~[na:1.8.0_121]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) ~[na:1.8.0_121]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682) ~[na:1.8.0_121]
	... 3 common frames omitted
Caused by: java.lang.ClassNotFoundException: expect to get instruction without BasicBlock already set
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:201) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.instrumentation.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:168) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.utils.generic.GenericClass.getClass(GenericClass.java:154) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.utils.generic.GenericClass.getClass(GenericClass.java:120) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.utils.generic.GenericClass.readObject(GenericClass.java:1706) ~[evosuite-current.jar:1.0.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2122) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) ~[na:1.8.0_121]
	at java.util.ArrayList.readObject(ArrayList.java:791) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2122) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:552) ~[na:1.8.0_121]
	at org.evosuite.testcase.DefaultTestCase.readObject(DefaultTestCase.java:1125) ~[evosuite-current.jar:1.0.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2122) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) ~[na:1.8.0_121]
	at java.util.ArrayList.readObject(ArrayList.java:791) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2122) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_121]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) ~[na:1.8.0_121]
	at sun.rmi.server.UnicastRef.unmarshalValue(UnicastRef.java:326) ~[na:1.8.0_121]
	at sun.rmi.server.UnicastServerRef.unmarshalParametersUnchecked(UnicastServerRef.java:631) ~[na:1.8.0_121]
	at sun.rmi.server.UnicastServerRef.unmarshalParameters(UnicastServerRef.java:619) ~[na:1.8.0_121]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:332) ~[na:1.8.0_121]
	... 12 common frames omitted
Caused by: java.lang.IllegalArgumentException: expect to get instruction without BasicBlock already set
	at org.evosuite.graphs.cfg.BasicBlock.appendInstruction(BasicBlock.java:231) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.graphs.cfg.BasicBlock.setInstructions(BasicBlock.java:212) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.graphs.cfg.BasicBlock.<init>(BasicBlock.java:110) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.graphs.cfg.RawControlFlowGraph.determineBasicBlockFor(RawControlFlowGraph.java:323) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.graphs.cfg.ActualControlFlowGraph.computeNodes(ActualControlFlowGraph.java:298) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.graphs.cfg.ActualControlFlowGraph.computeGraph(ActualControlFlowGraph.java:265) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.graphs.cfg.ActualControlFlowGraph.<init>(ActualControlFlowGraph.java:99) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.graphs.cfg.CFGGenerator.computeActualCFG(CFGGenerator.java:225) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.graphs.cfg.CFGGenerator.registerCFGs(CFGGenerator.java:105) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.graphs.cfg.CFGMethodAdapter.visitEnd(CFGMethodAdapter.java:233) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.shaded.org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.shaded.org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.shaded.org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.shaded.org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.shaded.org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.shaded.org.objectweb.asm.tree.ClassNode.accept(Unknown Source) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.instrumentation.BytecodeInstrumentation.transformBytes(BytecodeInstrumentation.java:275) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.instrumentation.InstrumentingClassLoader.getTransformedBytes(InstrumentingClassLoader.java:175) ~[evosuite-current.jar:1.0.4]
	at org.evosuite.instrumentation.InstrumentingClassLoader.instrumentClass(InstrumentingClassLoader.java:192) ~[evosuite-current.jar:1.0.4]
	... 80 common frames omitted
[MASTER] 04:03:47.032 [logback-1] WARN  TimeController - Phase SEARCH lasted too long, 172 seconds more than allowed.
* Minimizing test suite
[MASTER] 04:04:47.775 [logback-1] WARN  TestSuiteMinimizer - Minimization timeout. Roll back to original test suite
* Going to analyze the coverage criteria
* Coverage analysis for criterion STRONGMUTATION
* Coverage of criterion STRONGMUTATION: 26%
* Total number of goals: 2812
* Number of covered goals: 744
* Generated 6 tests with total length 76
* Resulting test suite's coverage: 26%
* Generating assertions
[MASTER] 04:06:30.522 [logback-1] WARN  TimeController - Current phase ASSERTION_GENERATION could run up to 300s, but only 241s are left
* Resulting test suite's mutation score: 2%
* Permissions denied during test execution: 
  - java.lang.RuntimePermission: 
         writeFileDescriptor: 8
* Writing JUnit test case 'FastMath_ESTest' to evosuite-strongmutation
* Done!

* Computation finished
```

**Comment by gofraser** [comment]
Java bytecode is limited to 64KB per method; since the mutation instrumentation can exceed this for large methods, there is the limit on the number of mutants that is added. Thus case 1 is just a general Java limitation, and the error originates in the JVM.

Is your case 2 actually related to the max_mutants_per_class parameter, or does this always happen?

**Comment by claudejin** [comment]
Thanks for your response.

Hm.. I believe it is actually related to the max_mutants_per_class parameter because it works properly when I change the parameter into the default value(1000) without adjusting anything else.

**Comment by gofraser** [comment]
If EvoSuite encounters a problem of exceeding the maximum bytecode size, it will try to deactivate mutation and re-instrument. I think that's as good as it gets, so I'm closing this issue. If there are still problems, please re-open.
